<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Econometria 2023/2024 - Giuseppe Ragusa - Sapienza">

<title>Econometria - Variabili Dummy and Dati Italiani</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href=".//files/icon-512.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Econometria</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./materiale.html"> 
<span class="menu-text">Materiale didattico</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./IntroduzioneR.html">R</a></li><li class="breadcrumb-item"><a href="./Dummy_ilfs.html">Variabili dummy</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Slides</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lezione12.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-slides" role="img">
</i> 
 <span class="menu-text">Lezione 1&amp;2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lezione34.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-slides" role="img">
</i> 
 <span class="menu-text">Lezione 3&amp;4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lezione67.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-slides" role="img">
</i> 
 <span class="menu-text">Lezione 6&amp;7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lezione8.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-slides" role="img">
</i> 
 <span class="menu-text">Lezione 8</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lezione9.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-slides" role="img">
</i> 
 <span class="menu-text">Lezione 9</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lezione10.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-slides" role="img">
</i> 
 <span class="menu-text">Lezione 10</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IntroduzioneR.html" class="sidebar-item-text sidebar-link"><i class="bi bi-filetype-html" role="img">
</i> 
 <span class="menu-text">Introduzione a <code>R</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Dummy_ilfs.html" class="sidebar-item-text sidebar-link active"><i class="bi bi-filetype-html" role="img">
</i> 
 <span class="menu-text">Variabili dummy</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#variabili-dummy" id="toc-variabili-dummy" class="nav-link active" data-scroll-target="#variabili-dummy">Variabili Dummy</a></li>
  <li><a href="#dati-sui-lavoratori-italiani" id="toc-dati-sui-lavoratori-italiani" class="nav-link" data-scroll-target="#dati-sui-lavoratori-italiani">Dati sui lavoratori italiani</a></li>
  <li><a href="#salari-per-genere" id="toc-salari-per-genere" class="nav-link" data-scroll-target="#salari-per-genere">Salari per genere</a>
  <ul class="collapse">
  <li><a href="#salari-per-regione" id="toc-salari-per-regione" class="nav-link" data-scroll-target="#salari-per-regione">Salari per regione</a></li>
  <li><a href="#gender-gap" id="toc-gender-gap" class="nav-link" data-scroll-target="#gender-gap">Gender gap</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./IntroduzioneR.html">R</a></li><li class="breadcrumb-item"><a href="./Dummy_ilfs.html">Variabili dummy</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Variabili Dummy and Dati Italiani</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="variabili-dummy" class="level2">
<h2 class="anchored" data-anchor-id="variabili-dummy">Variabili Dummy</h2>
<p>Le variabili <em>dummy</em> sono utilizzate per analizzare variabili categoriche.</p>
</section>
<section id="dati-sui-lavoratori-italiani" class="level2">
<h2 class="anchored" data-anchor-id="dati-sui-lavoratori-italiani">Dati sui lavoratori italiani</h2>
<p>Utilizeremo un dataset contenente alcuni variabili che descrivono le caratteristiche di una campione di lavoratori dipendenti italiani.</p>
<table class="table">
<colgroup>
<col style="width: 23%">
<col style="width: 76%">
</colgroup>
<thead>
<tr class="header">
<th>Variabile</th>
<th>Descrizione</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>retric</code></td>
<td>Retribuzione mensile netta</td>
</tr>
<tr class="even">
<td><code>genere</code></td>
<td>Genere del lavoratore</td>
</tr>
<tr class="odd">
<td><code>regione</code></td>
<td>Regione di residenza</td>
</tr>
<tr class="even">
<td><code>edulev</code></td>
<td>Livello di istruzione</td>
</tr>
<tr class="odd">
<td><code>istruzione_anni</code></td>
<td>Anni di istruzione completati</td>
</tr>
<tr class="even">
<td><code>eta</code></td>
<td>Età del lavoratore</td>
</tr>
<tr class="odd">
<td><code>titolo10</code></td>
<td>Titolo di studio</td>
</tr>
<tr class="even">
<td><code>detind</code></td>
<td>Tipo di contratto di lavoro (indeterminato, determinato)</td>
</tr>
<tr class="odd">
<td><code>piepar</code></td>
<td>Tipo di orario di lavoro (pieno, parziale)</td>
</tr>
<tr class="even">
<td><code>tenure</code></td>
<td>Anni di lavoro presso l’attuale datore di lavoro</td>
</tr>
<tr class="odd">
<td><code>cittadinanza</code></td>
<td>Se il lavoratore ha la cittadinanza italiana</td>
</tr>
<tr class="even">
<td><code>sg13</code></td>
<td>Luogo di nascita</td>
</tr>
<tr class="odd">
<td><code>orelav</code></td>
<td>Ore di lavoro settimanali</td>
</tr>
<tr class="even">
<td><code>genere_dummy</code></td>
<td>Variabile dummy per il genere (1 = Femmina, 0 = Maschio)</td>
</tr>
</tbody>
</table>
<p>Il file può essere scaricato <a href="https://bit.ly/ilfs">qua</a>.</p>
</section>
<section id="salari-per-genere" class="level2">
<h2 class="anchored" data-anchor-id="salari-per-genere">Salari per genere</h2>
<p>Consideriamo la variabile <code>genere</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df[, <span class="st">"genere"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 1
  genere 
  &lt;chr&gt;  
1 Maschio
2 Femmina
3 Femmina
4 Maschio
5 Maschio
6 Femmina</code></pre>
</div>
</div>
<p>La variabile assume il valore <code>maschio</code> o <code>femmina</code> a seconda che l’individua sia di genere maschile o femminile. Possiamo creare la variabile manualmente nel modo seguente</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Maschio =</span> <span class="fu">ifelse</span>(genere<span class="sc">==</span><span class="st">"Maschio"</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La variabile <code>Maschio</code> prende il valore 1 se il genere dell’individuo è maschile e 0 altrimenti.</p>
<p>Possiamo utilizzare questa variabile per analizzare la variabile genere. Per esempio, possiamo prendere la media di <code>Maschio</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>Maschio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5345987</code></pre>
</div>
</div>
<p>La media nel caso di una variabile dummy è la percentuale di osservazioni che prendono il valore uno. Nel caso dei nostri dati, <span class="math inline">\(\bar{X}_{maschi}=0.535\)</span> indica che circa il 53.46% dei lavoratori nel nostro campione è maschio.</p>
<p>Non c’è nulla di speciale nella scelta di “maschio” come valore per assegnare alla variabile dummy il valore 1. Possiamo infatti creare la variabile dummy <code>Femmina</code> con il valore 1 qualora il lavoratore sia di genere femminile.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Femmina =</span> <span class="fu">ifelse</span>(genere<span class="sc">==</span><span class="st">"Femmina"</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In questo caso, <span class="math inline">\(\bar{X}_{femmina}=0.465\)</span> indica che circa il 46.54 dei lavoratori nel nostro campione è una donna (questa percentuale non è altro che <span class="math inline">\(1-\bar{X}_{maschio}\)</span>.)</p>
<p>Come possiamo usare questa variabile in una regressione? Possiamo usare la dummy come variabile indipendente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>lm_maschi <span class="ot">&lt;-</span> <span class="fu">feols</span>(retric<span class="sc">~</span>Maschio, <span class="at">data =</span> df)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>lm_maschi</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: retric
Observations: 138,618 
Standard-errors: IID 
            Estimate Std. Error t value  Pr(&gt;|t|)    
(Intercept) 1171.258    1.99513 587.058 &lt; 2.2e-16 ***
Maschio      281.449    2.72871 103.144 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 506.7   Adj. R2: 0.071272</code></pre>
</div>
</div>
<p>L’interpretazione del coefficiente sulla dummy non è altro che la differenza dela salario fra uomini (<code>Maschio</code>=1) e donne (<code>Maschio</code>=0). Quindi, visto che <span class="math inline">\(\hat{\beta}_1 = 281.4492935\)</span>, gli uomini nel nostro campione guadagnano in media <span class="math inline">\(281.4492935\)</span> euro piu’ delle donne. L’intercetta è in questa regressione la media (sempre nel campione) del salario delle donne (l’intercetta è interpretabile come la media della variabile dipendente quando i regressori sono uguali a zero).</p>
<p>Se utilizziamo la dummy <code>Femmina</code> invece della variabile dummy <code>Maschio</code>, i coefficienti stimati saranno diversi, ma la loro interpetazione finale sarà identica.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>lm_femmine <span class="ot">&lt;-</span> <span class="fu">feols</span>(retric<span class="sc">~</span>Femmina, <span class="at">data =</span> df)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>lm_femmine</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: retric
Observations: 138,618 
Standard-errors: IID 
            Estimate Std. Error  t value  Pr(&gt;|t|)    
(Intercept) 1452.708    1.86154  780.381 &lt; 2.2e-16 ***
Femmina     -281.449    2.72871 -103.144 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 506.7   Adj. R2: 0.071272</code></pre>
</div>
</div>
<p>In questa nuova regression, <span class="math inline">\(\hat{\beta}_1 = 1452.7076446\)</span>, e quindi possiamo dire che le donne nel nostro campione guadagnano in media <span class="math inline">\(1452.7076446\)</span> euro in meno degli uomini. L’intercetta è invece la media del salario degli uomini.</p>
<p>Se calcolassimo le medie e la differenze delle medie manualemnte senza usare la regressione otterremo gli stessi risultati. Per esempio, il salario medio dei lavoratori di sesso maschile è esattamente uguale al coefficiente <span class="math inline">\(\hat{\beta}_0\)</span> nella regressione che usa la veriaile dummy <code>Femmina</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>retric[df<span class="sc">$</span>genere<span class="sc">==</span><span class="st">"Maschio"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1452.708</code></pre>
</div>
</div>
<p>Per avere una completa panaromica della media di <code>retric</code> per genere possiamo usare la funzione <code>group_by</code> e <code>summarize</code> di <code>dplyr</code>”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(genere) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="fu">mean</span>(retric))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  genere  `mean(retric)`
  &lt;chr&gt;            &lt;dbl&gt;
1 Femmina          1171.
2 Maschio          1453.</code></pre>
</div>
</div>
<p>I coefficienti delle due regressioni stimano i corrispondenti valori della popolazione: <span class="math inline">\(\hat{\beta}_0\)</span> stima la media nella popolazione dei salari per il caso in cui la variabile dummy è zero; <span class="math inline">\(\hat{\beta}_1\)</span> stima la differenza dei salari medi nella poplazione fra i lavoratori con variabile dummy uguale a 1 e variabile dummy uguale a zero. Quindi possiamo chiederci se questa differenza nei salari che vediamo nel campioni è probabile che permangano qualora avessimo a disposizione l’intera popolazione. L’intervallo di confidenza risponde a questa domanda fornendoci un intervallo di valori probabili della differenza salariale fra uomini e donne nel campione:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(lm_maschi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept) 1167.3479 1175.1688
Maschio      276.1011  286.7975</code></pre>
</div>
</div>
<p>Gli intervalli sono molto piccoli (come era prevedibile vista la grandezza del campione) e ci dice che questa differenza non è probabilmenmte dovuta al particolare compione che stiamo analizzando.</p>
<section id="salari-per-regione" class="level3">
<h3 class="anchored" data-anchor-id="salari-per-regione">Salari per regione</h3>
<p>Una variabile particolarmente interessante del nostro dataset è la variabile <code>regione</code> che fornisce la regione di residenza di ciascun lavoratore nel nostro campione</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df[,<span class="st">"regione"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 1
  regione  
  &lt;chr&gt;    
1 Puglia   
2 Lombardia
3 Piemonte 
4 Lombardia
5 Umbria   
6 Campania </code></pre>
</div>
</div>
<p>L’esistenza di differenza salariali nelle regioni italiane può essere investigata mediante un grafico che mostra la distribuzione di <code>retric</code> per ciascuna regione:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> retric)) <span class="sc">+</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Regione"</span>) <span class="sc">+</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Retribuzione netta"</span>) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span><span class="fu">stat</span>(density)))  <span class="sc">+</span> </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>          <span class="fu">element_text</span>(</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">angle =</span> <span class="dv">25</span>,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="fl">0.5</span>,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">hjust =</span> <span class="dv">1</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">size =</span> <span class="dv">6</span>), </span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> </span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>          <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>        ) <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>regione)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `stat(density)` was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(density)` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Dummy_ilfs_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">y =</span> retric, <span class="at">x =</span> <span class="fu">fct_reorder</span>(regione, retric))) <span class="sc">+</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Regione"</span>) <span class="sc">+</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Retribuzione netta"</span>) <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.alpha =</span> <span class="fl">0.6</span>)  <span class="sc">+</span> </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">angle =</span> <span class="dv">45</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">vjust =</span> <span class="fl">0.5</span>,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">hjust =</span> <span class="dv">1</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Dummy_ilfs_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Pur essendo una variabile categorica, <code>regione</code> prende piu’ di due valori e quindi non è possibile codificare l’informazione contenuta in essa mediante un’unica variabile dummy. In questo caso creiama una dummy <strong>per ciascuna regione</strong>: una dummy <code>Lombardia</code> che prende il valore 1 per quei lavoratori che risiedono in Lombardia e 0 per gli altri, una dummy <code>Sicilia</code> per i lavoratori che risiedono in Sicilia e 0 per gli altri, e così via.</p>
<p>E’ possibile creare queste dummy manualmente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Lombardia =</span> <span class="fu">ifelse</span>(regione<span class="sc">==</span><span class="st">"Lombardia"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">Sicilia =</span> <span class="fu">ifelse</span>(regione<span class="sc">==</span><span class="st">"Sicilia"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                    .</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>                    .</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>                    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La creazione manuale è però tediosa e prona ad errori. È preferibile automatizzare il processo di creazione delle dummy mediante il pachetto <code>fastDummies</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fastDummies)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> fastDummies<span class="sc">::</span><span class="fu">dummy_cols</span>(df, <span class="at">select_columns =</span> <span class="st">"regione"</span>, </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">omit_colname_prefix =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dopo l’esecuzione del codice, <code>df</code> conterrà una variabile dummy per ciascuna regione. Possiamo adesso calcolare la media di ciascuna dummy così creata per ottenere la percentuale dei residenti in ciascuna regione. Per esempio,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>Calabria)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01961506</code></pre>
</div>
</div>
<p>indica che circa il 1.96% dei lavoratori del nostro campione è residente in Calabria.</p>
<p>Qual è l’interpretazione della regressione in cui aggiungiamo tutte le dummy?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>lm_regione <span class="ot">&lt;-</span> <span class="fu">feols</span>(retric<span class="sc">~</span>Abruzzo<span class="sc">+</span>Basilicata<span class="sc">+</span> Calabria <span class="sc">+</span> Campania <span class="sc">+</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">Emilia Romagna</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Friuli Venezia Giulia</span><span class="st">`</span> <span class="sc">+</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>Lazio <span class="sc">+</span> Liguria <span class="sc">+</span> Lombardia <span class="sc">+</span> Marche <span class="sc">+</span> Molise<span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>Piemonte <span class="sc">+</span> Puglia <span class="sc">+</span> Sardegna <span class="sc">+</span> Sicilia <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>Toscana <span class="sc">+</span> <span class="st">`</span><span class="at">Trentino alto Adige</span><span class="st">`</span> <span class="sc">+</span> Umbria <span class="sc">+</span> </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">Valle d'Aosta</span><span class="st">`</span> <span class="sc">+</span> Veneto, <span class="at">data =</span> df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>The variable 'Veneto' has been removed because of collinearity (see $collin.var).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_regione)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: retric
Observations: 138,618 
Standard-errors: IID 
                          Estimate Std. Error    t value   Pr(&gt;|t|)    
(Intercept)             1352.67843    5.88778 229.743479  &lt; 2.2e-16 ***
Abruzzo                  -67.03866   11.67738  -5.740897 9.4372e-09 ***
Basilicata               -62.22983   10.73230  -5.798367 6.7108e-09 ***
Calabria                -159.50447   11.59058 -13.761558  &lt; 2.2e-16 ***
Campania                -124.70487    8.18131 -15.242653  &lt; 2.2e-16 ***
`Emilia Romagna`           8.80117    7.58301   1.160645 2.4579e-01    
`Friuli Venezia Giulia`    3.25957    9.44556   0.345090 7.3003e-01    
Lazio                    -30.97062    7.82437  -3.958227 7.5546e-05 ***
Liguria                   -2.50250   10.18666  -0.245665 8.0594e-01    
Lombardia                 56.13623    6.91684   8.115883 4.8617e-16 ***
Marche                   -76.95157   10.14049  -7.588549 3.2551e-14 ***
Molise                   -79.67389   14.50991  -5.490998 4.0037e-08 ***
Piemonte                 -12.44023    7.66513  -1.622964 1.0460e-01    
Puglia                  -139.24116    9.10816 -15.287521  &lt; 2.2e-16 ***
Sardegna                -150.99941   10.57937 -14.273005  &lt; 2.2e-16 ***
Sicilia                 -166.02165    7.95915 -20.859208  &lt; 2.2e-16 ***
Toscana                  -54.75509    8.10400  -6.756549 1.4187e-11 ***
`Trentino alto Adige`     81.81903    7.95858  10.280604  &lt; 2.2e-16 ***
Umbria                   -79.82247   10.44123  -7.644928 2.1040e-14 ***
`Valle d'Aosta`           14.82207    9.45899   1.566983 1.1712e-01    
... 1 variable was removed because of collinearity (Veneto)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 520.6   Adj. R2: 0.019842</code></pre>
</div>
</div>
<p>La funzione <code>feols</code> ci informa che una delle variabili dummy è stata rimossa per evitare la collinearità (la trappola delle variabili dummy). I coefficienti della regressione sono la differenza fra il salario medio nella regione a cui il coefficiente si riferisce e la regione omessa dalla regressione che, in questo caso, è la regione Veneto. Per esempio, il coefficite della dummy <code>Sicilia</code> ci dice che in media i lavoratori residenti nell’isola guadagnano 166.0216453 euro in meno dei lavoratori residenti in Veneto.</p>
<p>Aggiungere variabili dummy al modello di regressione è un’operazione così frequente che <code>R</code> possiede un meccanismo automatico per la loro gestione: aggiungere nella regressione la variabile categorica automaticamente crea e aggiunge al modello una dummy per ciascuna categoria.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">feols</span>(retric<span class="sc">~</span>regione, <span class="at">data=</span>df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: retric
Observations: 138,618 
Standard-errors: IID 
                               Estimate Std. Error    t value   Pr(&gt;|t|)    
(Intercept)                  1285.63977    10.0844 127.487822  &lt; 2.2e-16 ***
regioneBasilicata               4.80883    13.4986   0.356247 7.2166e-01    
regioneCalabria               -92.46581    14.1905  -6.516024 7.2442e-11 ***
regioneCampania               -57.66621    11.5743  -4.982284 6.2913e-07 ***
regioneEmilia Romagna          75.83983    11.1594   6.796071 1.0794e-11 ***
regioneFriuli Venezia Giulia   70.29823    12.4999   5.623892 1.8706e-08 ***
regioneLazio                   36.06804    11.3248   3.184884 1.4484e-03 ** 
regioneLiguria                 64.53616    13.0689   4.938129 7.8967e-07 ***
... 12 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 520.6   Adj. R2: 0.019842</code></pre>
</div>
</div>
<p>Se volessimo ottenere i risultati delle regressione omettando un’altra regione, possiamo usare la funzione <code>i()</code> che prende come pri argomento la variabile categorica e come secondo argomento la categoria da escludere. Pertanto, per escludere la dummy riferita alla regione Campania usiamo come regressore <code>i(regione, "Campanio")</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">feols</span>(retric<span class="sc">~</span><span class="fu">i</span>(regione, <span class="st">"Campania"</span>), <span class="at">data=</span>df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: retric
Observations: 138,618 
Standard-errors: IID 
                                Estimate Std. Error   t value   Pr(&gt;|t|)    
(Intercept)                    1227.9736    5.68048 216.17407  &lt; 2.2e-16 ***
regione::Abruzzo                 57.6662   11.57425   4.98228 6.2913e-07 ***
regione::Basilicata              62.4750   10.62000   5.88277 4.0437e-09 ***
regione::Calabria               -34.7996   11.48667  -3.02956 2.4495e-03 ** 
regione::Emilia Romagna         133.5060    7.42320  17.98496  &lt; 2.2e-16 ***
regione::Friuli Venezia Giulia  127.9644    9.31776  13.73339  &lt; 2.2e-16 ***
regione::Lazio                   93.7343    7.66960  12.22154  &lt; 2.2e-16 ***
regione::Liguria                122.2024   10.06826  12.13738  &lt; 2.2e-16 ***
... 12 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 520.6   Adj. R2: 0.019842</code></pre>
</div>
</div>
<p>Come nel caso della variabile <code>genere</code>, i valori dei coefficienti sono esattamenti uguali alle differenze delle medie calcolate manualmente. Per convincerci di ciò, possiamo calcolare la media di <code>retric</code> per regione e sottrarre la media della Campania usando la funzione <code>group_by</code> e <code>summarize</code> di <code>dplyr</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calcoliamo la media dei salari in Campania</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>mc <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(regione<span class="sc">==</span><span class="st">"Campania"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mc =</span> <span class="fu">mean</span>(retric)) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(mc)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="do">## `mc` e' uguale all'intercetta della regressione che </span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="do">## esclude la dummy per la Campania.</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Calcoliamo la media dei salari in ciascuna regione e sottraiamo</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="do">## `mc`</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(regione<span class="sc">!=</span><span class="st">"Campania"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(regione) <span class="sc">%&gt;%</span> </span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="st">`</span><span class="at">Differenza da media Campania</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>(retric)<span class="sc">-</span>mc) <span class="sc">%&gt;%</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="st">`</span><span class="at">Differenza da media Campania</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 19 × 2
   regione               `Differenza da media Campania`
   &lt;chr&gt;                                          &lt;dbl&gt;
 1 Sicilia                                        -41.3
 2 Calabria                                       -34.8
 3 Sardegna                                       -26.3
 4 Puglia                                         -14.5
 5 Umbria                                          44.9
 6 Molise                                          45.0
 7 Marche                                          47.8
 8 Abruzzo                                         57.7
 9 Basilicata                                      62.5
10 Toscana                                         69.9
11 Lazio                                           93.7
12 Piemonte                                       112. 
13 Liguria                                        122. 
14 Veneto                                         125. 
15 Friuli Venezia Giulia                          128. 
16 Emilia Romagna                                 134. 
17 Valle d'Aosta                                  140. 
18 Lombardia                                      181. 
19 Trentino alto Adige                            207. </code></pre>
</div>
</div>
<p>Il vantaggio di usare la regressione rispetto a calcolare la differenza medie manualmente è la regressione ci restituisce gli errori standard delle differenze delle media consentendoci la costruzione immediata degli intervalli di confidenza.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(lm_regione)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              2.5 %      97.5 %
(Intercept)             1341.138502 1364.218367
Abruzzo                  -89.926111  -44.151208
Basilicata               -83.264940  -41.194721
Calabria                -182.221796 -136.787151
Campania                -140.740079 -108.669653
`Emilia Romagna`          -6.061372   23.663721
`Friuli Venezia Giulia`  -15.253560   21.772697
Lazio                    -46.306226  -15.635005
Liguria                  -22.468156   17.463149
Lombardia                 42.579363   69.693096
Marche                   -96.826733  -57.076413
Molise                  -108.113045  -51.234739
Piemonte                 -27.463752    2.583285
Puglia                  -157.092974 -121.389340
Sardegna                -171.734783 -130.264047
Sicilia                 -181.621436 -150.421854
Toscana                  -70.638786  -38.871401
`Trentino alto Adige`     66.220357   97.417696
Umbria                  -100.287085  -59.357850
`Valle d'Aosta`           -3.717364   33.361506</code></pre>
</div>
</div>
</section>
<section id="gender-gap" class="level3">
<h3 class="anchored" data-anchor-id="gender-gap">Gender gap</h3>
<p>L’obiettivo è misurare la differenza salariale tra donne e uomini che condividono le stesse caratteristiche rilevanti, come l’istruzione, l’esperienza lavorativa, il settore di impiego, ecc., ma differiscono per genere.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>lm_gp <span class="ot">&lt;-</span> <span class="fu">feols</span>(retric<span class="sc">~</span>genere<span class="sc">+</span>regione, <span class="at">data=</span>df)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>lm_gp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: retric
Observations: 138,618 
Standard-errors: IID 
                                Estimate Std. Error    t value   Pr(&gt;|t|)    
(Intercept)                  1118.134158    9.81249 113.950063  &lt; 2.2e-16 ***
genereMaschio                 290.437520    2.70004 107.568035  &lt; 2.2e-16 ***
regioneBasilicata               0.001989   12.96823   0.000153 9.9988e-01    
regioneCalabria               -91.809556   13.63291  -6.734407 1.6524e-11 ***
regioneCampania               -65.965371   11.11971  -5.932295 2.9944e-09 ***
regioneEmilia Romagna          95.899709   10.72248   8.943802  &lt; 2.2e-16 ***
regioneFriuli Venezia Giulia   86.855842   12.00973   7.232126 4.7793e-13 ***
regioneLazio                   48.195564   10.88033   4.429603 9.4479e-06 ***
... 13 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 500.1   Adj. R2: 0.095359</code></pre>
</div>
</div>
<p>In questa prima regressione stiamo “controllando” per la regione di residenza. L’interpretazione del coefficiente di gender è quindi la differenza media dei salari fra uomini e donne a parità di regione di residenza. La stima di tale differenza è di circa 290.44 euro. Questa differenza è statisticamente significativa, cioè possiamo rigettare l’ipotesi nulla che nella popolazione la differenza è uguale a zero (<span class="math inline">\(H_0: \beta_1=0\)</span>) poichè l’intervallo di onfidenza non contiene zero o, equivalentemente, la statistica <span class="math inline">\(t\)</span> è maggiore in valore assoluto del valore critico (<span class="math inline">\(1.96\)</span>).</p>
<p>Chiaramente, uomini e donne possono differire per livelli di istruzione (<code>istruzione_anno</code>), per la tipologia di contratto (<code>detind</code>) e se lavorano in part-time (<code>piepar</code>) e per il numero di ore lavorate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>lm_gp2 <span class="ot">&lt;-</span> <span class="fu">feols</span>(retric<span class="sc">~</span>istruzione_anni<span class="sc">+</span>piepar<span class="sc">+</span>detind<span class="sc">+</span>genere<span class="sc">+</span>regione, <span class="at">data=</span>df)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>lm_gp2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: retric
Observations: 138,618 
Standard-errors: IID 
                            Estimate Std. Error    t value   Pr(&gt;|t|)    
(Intercept)               -19.714271   8.840365  -2.230029 2.5747e-02 *  
istruzione_anni            41.355406   0.261081 158.400638  &lt; 2.2e-16 ***
piepartempo pieno         521.552688   2.792073 186.797681  &lt; 2.2e-16 ***
detindtempo indeterminato 286.402687   2.939087  97.446140  &lt; 2.2e-16 ***
genereMaschio             201.536591   2.283682  88.250741  &lt; 2.2e-16 ***
regioneBasilicata          -0.101848  10.224505  -0.009961 9.9205e-01    
regioneCalabria           -39.440407  10.749966  -3.668887 2.4370e-04 ***
regioneCampania           -42.821891   8.767499  -4.884163 1.0398e-06 ***
... 16 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 394.3   Adj. R2: 0.437681</code></pre>
</div>
</div>
<p>Per tenere conto delle ore lavorate (<code>orelav</code>) possiamo usare come variabile dipendente il rapporto fra il salario orario netto mensile e le ore lavorete nel mese (che è uguale a <span class="math inline">\(4\times orelav\)</span>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>lm_gp3 <span class="ot">&lt;-</span> <span class="fu">feols</span>(<span class="fu">I</span>(retric<span class="sc">/</span>(<span class="dv">4</span><span class="sc">*</span>orelav))<span class="sc">~</span>istruzione_anni<span class="sc">+</span>piepar<span class="sc">+</span>detind<span class="sc">+</span>genere<span class="sc">+</span>regione, <span class="at">data=</span>df)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>lm_gp3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: I(retric/(4 * orelav))
Observations: 138,618 
Standard-errors: IID 
                           Estimate Std. Error   t value   Pr(&gt;|t|)    
(Intercept)                3.724961   0.201074 18.525280  &lt; 2.2e-16 ***
istruzione_anni            0.403373   0.005938 67.927402  &lt; 2.2e-16 ***
piepartempo pieno         -0.178177   0.063506 -2.805674 5.0218e-03 ** 
detindtempo indeterminato  1.799457   0.066850 26.917971  &lt; 2.2e-16 ***
genereMaschio              0.287500   0.051942  5.534970 3.1184e-08 ***
regioneBasilicata         -0.158508   0.232557 -0.681588 4.9550e-01    
regioneCalabria           -0.462131   0.244508 -1.890040 5.8755e-02 .  
regioneCampania           -0.312879   0.199417 -1.568968 1.1666e-01    
... 16 coefficients remaining (display them with summary() or use argument n)
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 8.96792   Adj. R2: 0.040316</code></pre>
</div>
</div>
<section id="esercizi" class="level4">
<h4 class="anchored" data-anchor-id="esercizi">Esercizi:</h4>
<ol type="a">
<li><p>Come possiamo interpretare il coefficiente su <code>genereMaschio</code> nell’ultima regressione? Per esempio, come è possibile interpretare la grandezza del coefficiente in maniera percentuale (per esemptio, di quanto è più alto il salario degli uomini in termini percentuali rispetto a quello delle donne?)</p></li>
<li><p>La differenza fra i salari fra uomini e donne nell’ultima regression è statisticamente significativa?</p></li>
<li><p>Quali sono le altre variabili che è probabile possono influenzare l’interpretezione del coefficiente su <code>genereMaschio</code> come indicativo di discriminazione?</p></li>
</ol>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>