<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.326">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Giuseppe Ragusa">
<meta name="description" content="Elementi di Econometria 2022/2023 - Giuseppe Ragusa - Sapienza">

<title>Econometria - R: Introduzione</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href=".//files/icon-512.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script src="site_libs/quarto-contrib/iconify-1.0.0-beta.2/iconify-icon.min.js"></script>
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Econometria</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./syllabus.html" rel="" target="">
 <span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./programma.html" rel="" target="">
 <span class="menu-text">Programma del corso</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./materiale.html" rel="" target="">
 <span class="menu-text">Materiale didattico</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./risorse.qmd" rel="" target="">
 <span class="menu-text">Risorse</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">R: Introduzione</li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Introduzione</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./../Lecture13.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1: Introduzione all’econometria <i class="fa-brands fa-slideshare" aria-label="slideshare"></i></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./../Lecture13b.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2: Richiami di probabilità e statistica <i class="fa-brands fa-slideshare" aria-label="slideshare"></i></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./../IntroduzioneR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3a: Introduzione ad R <iconify-icon inline="" icon="carbon:logo-r-script"></iconify-icon></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./../IntroduzioneR.Rmd" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3b: Introduzione ad R <i class="fa-solid fa-laptop-code" aria-label="laptop-code"></i></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Modello Lineare Univariato</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./../Lecture45.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4&amp;5: Formalizzazione e stima <i class="fa-brands fa-slideshare" aria-label="slideshare"></i></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Modello Lineare Multivariato</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./../Lecture67.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6&amp;7: Modello multivariato <i class="fa-brands fa-slideshare" aria-label="slideshare"></i></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./../Lecture8.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8: Inferenza <i class="fa-brands fa-slideshare" aria-label="slideshare"></i></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./../Lecture9.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9: Modelli non-lineari <i class="fa-brands fa-slideshare" aria-label="slideshare"></i></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Modelli per probabilià</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./../Lecture10.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10: LPM, Logit, Probit <i class="fa-brands fa-slideshare" aria-label="slideshare"></i></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">11: Panel data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./../panel.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Panel data</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">12: Variabili strumentali</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./../iv.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IV</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#storia" id="toc-storia" class="nav-link active" data-scroll-target="#storia">Storia</a></li>
  <li><a href="#installazione-di-r-e-rstudio" id="toc-installazione-di-r-e-rstudio" class="nav-link" data-scroll-target="#installazione-di-r-e-rstudio">Installazione di <code>R</code> e <code>Rstudio</code></a></li>
  <li><a href="#installazione-di-pacchetti" id="toc-installazione-di-pacchetti" class="nav-link" data-scroll-target="#installazione-di-pacchetti">Installazione di pacchetti</a></li>
  <li><a href="#caricamento-pacchetti" id="toc-caricamento-pacchetti" class="nav-link" data-scroll-target="#caricamento-pacchetti">Caricamento pacchetti</a></li>
  <li><a href="#i-dataset-di-ecdat" id="toc-i-dataset-di-ecdat" class="nav-link" data-scroll-target="#i-dataset-di-ecdat">I dataset di <code>Ecdat</code></a></li>
  <li><a href="#primi-grafici-con-ggplot2" id="toc-primi-grafici-con-ggplot2" class="nav-link" data-scroll-target="#primi-grafici-con-ggplot2">Primi grafici con <code>ggplot2</code></a></li>
  <li><a href="#prime-manipolazione-di-dati-usando-dplyr" id="toc-prime-manipolazione-di-dati-usando-dplyr" class="nav-link" data-scroll-target="#prime-manipolazione-di-dati-usando-dplyr">Prime manipolazione di dati usando <code>dplyr</code></a></li>
  <li><a href="#qualcosa-di-più-complicato" id="toc-qualcosa-di-più-complicato" class="nav-link" data-scroll-target="#qualcosa-di-più-complicato">Qualcosa di più complicato</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">R: Introduzione</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Giuseppe Ragusa </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="storia" class="level2">
<h2 class="anchored" data-anchor-id="storia">Storia</h2>
<p><code>R</code> è un linguaggio di programmazione open source utilizzato per l’analisi e visualizzazione dei dati.</p>
<p><code>R</code> è la versione open source di <code>S</code>, software sviluppato da John Chambers e colleghi presso i Bell Laboratories di AT&amp;T alla fine degli anni ’70. Nell’idea del suo creatore <code>S</code> doveva essere un linguaggio di programmazione per l’analisi dei dati che fosse più semplice e più interattivo rispetto ai linguaggi esistenti dell’epoca, come FORTRAN e SAS.</p>
<p><code>R</code> fu sviluppato inizialmente da Ross Ihaka e Robert Gentleman presso l’Università di Auckland, in Nuova Zelanda. La prima versione di <code>R</code> venne condivisa dai sui creatori nel 1993. Nel 1995 il software fu rilasciato sotto la licenza open source GNU GPL.</p>
<p>La versione 1.0 è stata rilasciata il 29 febbraio 2000 e da quel momento la crescita in popolarità non si è mai arrestata.</p>
<p>Negli ultimi dieci anni, due aziende hanno contribuito alla crescita di <code>R:</code> R Studio (oggi diventata Posit) e Revolution Analytics.</p>
<p><a href="https://blog.revolutionanalytics.com/2015/04/revolution-analytics-microsoft.html">Revolution Analytics</a> fondata nel 2007, è stata una delle prime società ad offrire una versione commerciale di <code>R</code>. Revolution Analytics ha introdotto nuove funzionalità, come l’elaborazione parallela e distribuita, che hanno permesso di elaborare grandi quantità di dati in modo più efficiente.</p>
<p>L’acquisizione di Revolution Analytics da parte di Microsoft nel 2015 ha ulteriormente rafforzato l’adozione di R, poiché Microsoft ha iniziato ad integrare R in molti dei suoi prodotti, come SQL Server e Power BI.</p>
<p>RStudio è stata fondata nel 2011 da JJ Allaire ed ha cambiato nome in <a href="htpps://posit.com">Posit</a> nel 2022. RStudio ha creato un ambiente di sviluppo integrato (IDE) per R, chiamato appunto <a href="https://posit.co/products/open-source/rstudio/">RSudio</a>, che semplifica lo sviluppo di codice R, la gestione dei pacchetti e la creazione di grafici. <a href="https://posit.co/products/open-source/rstudio/">RSudio</a> è diventato uno strumento fondamentale per molti utenti R, poiché semplifica notevolmente il processo di sviluppo e di debugging.</p>
<p>RStudio ha inoltre creato e mantiene pacchetti importanti come <code>ggplot2()</code> e <code>dplyr()</code>, che hanno migliorato notevolmente la capacità di R per la visualizzazione dei dati e la manipolazione dei dati.</p>
<p>R è oggi uno dei linguaggi di programmazione più popolari per l’analisi dei dati e la statistica negli ultimi anni. Ecco alcuni dati sull’adozione di R:</p>
<ul>
<li><p>Numero di utenti: Secondo un sondaggio del 2022 condotto da <a href="https://insights.stackoverflow.com/survey/2021">Stack Overflow</a> R è uno dei linguaggi di programmazione più popolare al mondo, utilizzato dal 4.7% degli sviluppatori. Nella lista è il primo software ad essere specificatamente pensato per applicazioni statistiche.</p></li>
<li><p>Numero di pacchetti: Il Comprehensive R Archive Network (<a href="https://cran.r-project.org/">CRAN</a>), il principale repository di pacchetti per R, contiene oltre 19.000 pacchetti. Questi pacchetti coprono una vasta gamma di applicazioni che vanno dalla statistica al machine learning, dalla visualizzazione e manipolazione dei dati alla stesura automatica di report, e altri task generici e non necessariamente legati alle applicazioni di carattere statistico.</p></li>
<li><p>Popolarità dei pacchetti: <code>ggplot2</code> (per la visualizzazione dei dati) e <code>dplyr</code> (per la manipolazione dei dati) sono fra i pacchetti più popolari.</p></li>
<li><p>Uso aziendale: L’adozione di R nell’ambiente aziendale è aumentata negli ultimi anni, con molte aziende che lo utilizzano per l’analisi dei dati e la statistica.</p></li>
</ul>
<p>In generale, <code>R</code> è diventato un linguaggio di programmazione popolare tra i data scientist, gli statistici e gli analisti dei dati grazie alla sua vasta gamma di pacchetti, alla sua flessibilità e alla sua potenza nell’analisi dei dati.</p>
</section>
<section id="installazione-di-r-e-rstudio" class="level2">
<h2 class="anchored" data-anchor-id="installazione-di-r-e-rstudio">Installazione di <code>R</code> e <code>Rstudio</code></h2>
<p>Per iniziare ad utilizzare R, è necessario installare il software. R può essere scaricato gratuitamente dal sito ufficiale (<a href="https://www.r-project.org/">www.r-project.org/</a>) scegliendo la versione adatta al sistema operativo utilizzato.</p>
<p>Per installare RStudio sul tuo computer basta visitare <a href="https://posit.co/download/rstudio-desktop/">https://posit.co/download/rstudio-desktop/</a>, scaricare la versione di RStudio Desktop compatibile con il sistema operativo e seguire le istruzioni per completare l’installazione.</p>
</section>
<section id="installazione-di-pacchetti" class="level2">
<h2 class="anchored" data-anchor-id="installazione-di-pacchetti">Installazione di pacchetti</h2>
<p>Per utilizzare pacchetti aggiuntivi come <code>ggplot2</code> e <code>dplyr</code>, è necessario installarli utilizzando il comando <strong><code>install.packages()</code></strong> seguito dal nome del pacchetto da installare.</p>
<p>Ad esempio, per installare il pacchetto <code>ggplot2</code>, bisogna digitare il seguente comando nella console <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ggplot2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Per installare <code>dplyr</code> bisogna usare il seguente comando:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ggplot2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Un pacchetto particolarmente utile poiché contiene parecchi dataset di carattere economico, è <code>Ecdat</code>. Può essere installato mediante il seguente comando:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"Ecdat"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Alternativamente, i pacchetti possono essere installati direttamente da <code>RStudio</code> usando il menu <em>Tools</em> (<em>Strumenti</em>).</p>
</section>
<section id="caricamento-pacchetti" class="level2">
<h2 class="anchored" data-anchor-id="caricamento-pacchetti">Caricamento pacchetti</h2>
<p>L’installazione rende disponibili i pacchetti sul proprio computer. Perché <code>R</code> possa utilizzare le funzionalità del pacchetto è necessario caricare i pacchetti utilizzando il comando <strong><code>library()</code></strong>. Ad esempio, per caricare il pacchetto <code>Ecdat</code> bisogna eseguire il seguente comando nella console R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Ecdat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="i-dataset-di-ecdat" class="level2">
<h2 class="anchored" data-anchor-id="i-dataset-di-ecdat">I dataset di <code>Ecdat</code></h2>
<p>Per avere un’idea dei dataset messi a disposizione da <code>Ecdat</code> possiamo utilizzare la funzione di <code>help</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(<span class="at">package=</span><span class="st">"Ecdat"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Il sistema di help di <code>R</code> è un’importante risorsa per gli utenti che utilizzano questo software. Consente di accedere a informazioni dettagliate su tutte le funzioni e i pacchetti di <code>R</code>, nonché di comprendere meglio il funzionamento del linguaggio di programmazione R.</p>
<p>Ogni funzione in R ha la sua pagina di help, alla quale si può accedere tramite la funzione <code>help()</code> o tramite il simbolo ? seguito dal nome della funzione. Per esempio</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>apre la pagina di help relativa alla funzione <code>mean</code>.</p>
<p>La pagina di help fornisce una descrizione della funzione, i suoi argomenti e tipologia dei valori che la funzione restituisce. Inoltre, la maggior parte delle funzioni in R hanno esempi di utilizzo nella loro pagina di help.</p>
<p>Per ottenere aiuto su un pacchetto e sulle sue funzionalità bisgna passare l’argomento <code>packages</code> seguito dal nome del pacchetto. Per esempio, il seguente comando mostra la pagina di <code>help</code> per il pacchetto <code>ggplot2</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(<span class="at">packages=</span><span class="st">"ggplot2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>I dataset possono essere caricati nella sessione di <code>R</code> mediante il comando <strong><code>data()</code></strong>. Per esempio, il seguente comando</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Caschool)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>rende disponibile il dataset <code>Caschool</code>. Il data set può essere richiamato semplicemente digitando il suo nome</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Caschool)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    distcod              county                         district     grspan   
 Min.   :61382   Sonoma     : 29   Lakeside Union Elementary:  3   KK-06: 61  
 1st Qu.:64308   Kern       : 27   Mountain View Elementary :  3   KK-08:359  
 Median :67760   Los Angeles: 27   Jefferson Elementary     :  2              
 Mean   :67473   Tulare     : 24   Liberty Elementary       :  2              
 3rd Qu.:70419   San Diego  : 21   Ocean View Elementary    :  2              
 Max.   :75440   Santa Clara: 20   Pacific Union Elementary :  2              
                 (Other)    :272   (Other)                  :406              
    enrltot           teachers          calwpct          mealpct      
 Min.   :   81.0   Min.   :   4.85   Min.   : 0.000   Min.   :  0.00  
 1st Qu.:  379.0   1st Qu.:  19.66   1st Qu.: 4.395   1st Qu.: 23.28  
 Median :  950.5   Median :  48.56   Median :10.520   Median : 41.75  
 Mean   : 2628.8   Mean   : 129.07   Mean   :13.246   Mean   : 44.71  
 3rd Qu.: 3008.0   3rd Qu.: 146.35   3rd Qu.:18.981   3rd Qu.: 66.86  
 Max.   :27176.0   Max.   :1429.00   Max.   :78.994   Max.   :100.00  
                                                                      
    computer         testscr         compstu           expnstu    
 Min.   :   0.0   Min.   :605.5   Min.   :0.00000   Min.   :3926  
 1st Qu.:  46.0   1st Qu.:640.0   1st Qu.:0.09377   1st Qu.:4906  
 Median : 117.5   Median :654.5   Median :0.12546   Median :5215  
 Mean   : 303.4   Mean   :654.2   Mean   :0.13593   Mean   :5312  
 3rd Qu.: 375.2   3rd Qu.:666.7   3rd Qu.:0.16447   3rd Qu.:5601  
 Max.   :3324.0   Max.   :706.8   Max.   :0.42083   Max.   :7712  
                                                                  
      str            avginc           elpct           readscr     
 Min.   :14.00   Min.   : 5.335   Min.   : 0.000   Min.   :604.5  
 1st Qu.:18.58   1st Qu.:10.639   1st Qu.: 1.941   1st Qu.:640.4  
 Median :19.72   Median :13.728   Median : 8.778   Median :655.8  
 Mean   :19.64   Mean   :15.317   Mean   :15.768   Mean   :655.0  
 3rd Qu.:20.87   3rd Qu.:17.629   3rd Qu.:22.970   3rd Qu.:668.7  
 Max.   :25.80   Max.   :55.328   Max.   :85.540   Max.   :704.0  
                                                                  
    mathscr     
 Min.   :605.4  
 1st Qu.:639.4  
 Median :652.5  
 Mean   :653.3  
 3rd Qu.:665.9  
 Max.   :709.5  
                </code></pre>
</div>
</div>
</section>
<section id="primi-grafici-con-ggplot2" class="level2">
<h2 class="anchored" data-anchor-id="primi-grafici-con-ggplot2">Primi grafici con <code>ggplot2</code></h2>
<p>I passi per ottenere un grafico con <code>ggplot2</code> sono:</p>
<ol type="1">
<li><p>Installare e caricare il pacchetto <code>ggplot2</code> utilizzando il comando <code>install.packages("ggplot2")</code> seguito da <code>library(ggplot2)</code>.</p></li>
<li><p>Caricare i dati che si desidera visualizzare in un data frame.</p></li>
<li><p>Creare un oggetto <code>ggplot</code> utilizzando la funzione <code>ggplot()</code>. Gli argomenti di questa funzione sono il <code>data.frame</code> e la funzione <code>aes</code> mediante la quale possono essere specificate le variabili che si desidera utilizzare per l’asse x e l’asse y.</p></li>
<li><p>Aggiungere i livelli e gli stili al grafico utilizzando una serie di geometrie come <code>geom_point()</code>, <code>geom_line()</code>, <code>geom_bar()</code>. Queste funzioni definiscono le modalità di rappresentazione dei dati nel grafico (ad esempio, con punti, linee, barre, ecc.).</p></li>
<li><p>Aggiungere etichette, titoli e altre personalizzazioni utilizzando funzioni come <code>labs()</code>, <code>xlab()</code>, <code>ylab()</code>, <code>ggtitle()</code> e altre funzioni di personalizzazione.</p></li>
</ol>
<p>Ecco un esempio di codice di base per creare un grafico a dispersione utilizzando ggplot2:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Caricare i dati</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Caschool)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Creare l'oggetto ggplot</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>scatterplot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Caschool, <span class="fu">aes</span>(<span class="at">x =</span> str, <span class="at">y =</span> testscr))</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggiungere i punti al grafico</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>scatterplot <span class="ot">&lt;-</span> scatterplot <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">col =</span> <span class="st">"darkgreen"</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggiungere etichette e titoli</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>scatterplot <span class="ot">&lt;-</span> scatterplot <span class="sc">+</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Grafico a dispersione - testscr/str"</span>,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">"Rapporto studenti insegnanti"</span>, <span class="at">y =</span> <span class="st">"Punteggi nei test"</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizzare il grafico</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>scatterplot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="IntroduzioneR_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Questo è solo un esempio molto semplice, ma <code>ggplot2</code> offre molte altre funzionalità per la creazione di grafici avanzati e personalizzati. Per esempio, possiamo cambiare il tema grafico usando <code>theme_bw()</code> che elimina i colori</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>scatterplot <span class="ot">&lt;-</span> scatterplot <span class="sc">+</span> <span class="fu">theme_bw</span>()</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>scatterplot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="IntroduzioneR_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Possiamo anche costruire grafici raggruppati per variabile. Per ottenere un grafico a dispersione per <code>str</code> e <code>testscr</code> per le due tipologie di scuole <code>grspan=="KK-06" e</code>grspan=“KK-08”`:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>scatterplot <span class="ot">&lt;-</span> scatterplot <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>grspan)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>scatterplot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="IntroduzioneR_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>La funzione facet_wrap() in ggplot2 è utilizzata per dividere i dati in sottoinsiemi basati su una variabile e creare una griglia di grafici separati, ognuno dei quali visualizza i dati per uno dei livelli della variabile.</p>
<p>La sintassi di base di facet_wrap() è la seguente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">facet_wrap</span>(<span class="sc">~</span>variable, <span class="at">nrow =</span> x, <span class="at">ncol =</span> y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dove <code>variable</code> è la variabile che si vuole utilizzare per suddividere i dati in sottoinsiemi (nell precedente esempio abbiamo utilizzato `<code>),</code>nrow<code>e</code>ncol` specificano il numero di righe e colonne della griglia di grafici che si desidera creare.</p>
</div>
</div>
<p>Possiamo anche aggiungere le rette di regression a ciascun grafico usando la geometria <code>geom_smooth</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>scatterplot <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">col =</span> <span class="st">"darkred"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="IntroduzioneR_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="prime-manipolazione-di-dati-usando-dplyr" class="level2">
<h2 class="anchored" data-anchor-id="prime-manipolazione-di-dati-usando-dplyr">Prime manipolazione di dati usando <code>dplyr</code></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
</div>
<p>Calcoliamo la media e la standard deviation di <code>testscr</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>Caschool <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">m =</span> <span class="fu">mean</span>(testscr), <span class="at">s =</span> <span class="fu">sd</span>(testscr))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         m        s
1 654.1565 19.05335</code></pre>
</div>
</div>
<p>Possiamo anche calcolare la media, la standard deviation e il numero di osservazioni per il gruppo di scuole che hanno un rapporto studenti insegnanti minore di 20, <span class="math inline">\(str&lt;20\)</span> e il gruppo di scuole che hanno un rapporto maggiore o uguale a venti (<span class="math inline">\(str&gt;20\)</span>) usando la funzione <code>group_by</code> seguita dall’indicazione del gruppo (nel nostro caso <code>str&lt;20</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>df_1 <span class="ot">&lt;-</span> Caschool <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(str<span class="sc">&lt;</span><span class="dv">20</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">m =</span> <span class="fu">mean</span>(testscr),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">s =</span> <span class="fu">sd</span>(testscr),</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Il risultato delle manipolazioni è un <code>tibble</code> — un sorta di <code>data.frame</code> più flessibile definito nel pacchetto <code>dplyr</code>.</p>
<p><code>df_1</code> può essere a sua volta utilizzato per altri calcoli e si comporta in tutto e per tutto come un normale <code>data.frame</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>df_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  `str &lt; 20`     m     s     n
  &lt;lgl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1 FALSE       650.  17.9   182
2 TRUE        657.  19.4   238</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Le maggiori differenze fra i <code>tibble</code> e i <code>data.frame</code> sono:</p>
<ul>
<li><p>Tipo di output: Il metodo di visualizzazione di un tibble è più compatto e leggibile rispetto a quello di un data.frame.</p></li>
<li><p>Comportamento dei nomi delle variabili: in un <code>tibble</code>, i nomi delle variabili sono sempre conservati e non vengono mai modificati (ad esempio, i nomi delle variabili non vengono convertiti in stringhe). In un <code>data.frame</code>, i nomi delle variabili possono essere modificati o convertiti in stringhe.</p></li>
<li><p>Comportamento di default dei dati mancanti: in un <code>tibble</code>, i dati mancanti vengono visualizzati in modo più chiaro rispetto a un <code>data.frame</code>.</p></li>
<li><p>Comportamento della subsetting: in un <code>tibble</code>, il subsetting (o l’estrazione di sottoinsiemi di dati) è più rigoroso rispetto a un <code>data.frame</code>, in quanto conserva sempre la classe del <code>tibble</code>, anche se viene restituito un singolo valore.</p></li>
<li><p>Funzioni dplyr: un <code>tibble</code> è progettato per essere compatibile con le funzioni del pacchetto dplyr, che sono utilizzate per manipolare i dati.</p></li>
</ul>
<p>I <code>tibble</code> sono una versione leggermente migliorata dei tradizionali <code>data.frame</code>, progettata per semplificare l’analisi dei dati in <code>R</code>. Tuttavia, i <code>data.frame</code> sono ancora molto utilizzati e sono l’oggetto dati di base per molti pacchetti in R. Fortunatamente, molti dei comandi di <code>R</code> disegnati per i <code>data.frame</code> funzionano anche per i <code>tibble</code>.</p>
</div>
</div>
<p>Abbiamo visto che una stima della differenza dei valori attesi fra i due gruppi <span class="math display">\[
\Delta = E(testscr|str&lt;20) - E(testscr|str\geqslant20)
\]</span> può essere ottenuta calcolando la differenza delle medie campionarie dei due gruppi e può essere ottenuta usando le informazioni in <code>df_1</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Differenza delle medie campionarie</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>df_1<span class="sc">$</span>m[<span class="dv">2</span>]<span class="sc">-</span>df_1<span class="sc">$</span>m[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.37241</code></pre>
</div>
</div>
<p>e, quindi, <span class="math display">\[
\hat{\Delta} = \overline{testscr}_{str&lt;20} - \overline{testscr}_{str\geqslant20} = 7.3724101.
\]</span></p>
<p>Con le stesse informazioni è possibile calcolare l’intervallo di confidenza al 95% per <span class="math inline">\(\Delta\)</span> che è dato da <span class="math display">\[
\hat{\Delta}\pm1.96\times\sqrt{\frac{s_{str&lt;20}^{2}}{n_{str&lt;20}}+\frac{s_{str\geqslant20}^{2}}{n_{str\geqslant20}}}.
\]</span> Usando le informazioni contenute in <code>df_1</code> otteniamo: <span class="math display">\[
(3.7979806, 10.9468397)
\]</span></p>
</section>
<section id="qualcosa-di-più-complicato" class="level2">
<h2 class="anchored" data-anchor-id="qualcosa-di-più-complicato">Qualcosa di più complicato</h2>
<p>Invece di stimare la variazione del valore atteso rispetto alle due macro-categorie (<span class="math inline">\(str&lt;20\)</span> e <span class="math inline">\(str\geqslant20\)</span>) possiamo provare a stimare il valore atteso condizionatamente a piccoli intervalli. Per esempio, possiamo voler stimare la seguente differenza <span class="math display">\[
E(testscr|20.1 &lt; str \leqslant 20.6) - E(testscr|20.6 &lt; str \leqslant 21.1)
\]</span> oppure <span class="math display">\[
E(testscr|21.6 &lt; str \leqslant 22) - E(testscr|22 &lt; str \leqslant 22.5).
\]</span></p>
<p>Per stimare queste quantità utilizzando i dati nel campion, è necessario calcolare la media campionaria per le scuole che hanno un <span class="math inline">\(str\)</span> che appartiene a ciascun intervallo. Per costruire questi intervalli, possiamo utilizzare la funzione <code>cut()</code>. La funzione <code>cut()</code> è utilizzata per suddividere un vettore numerico in più intervalli.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>La sintassi della funzione cut() è la seguente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cut</span>(x, breaks,</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">labels =</span> <span class="cn">NULL</span>,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">include.lowest =</span> <span class="cn">FALSE</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">right =</span> <span class="cn">TRUE</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">dig.lab =</span> <span class="dv">3</span>, ...)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>dove:</p>
<ul>
<li><code>x</code> è il vettore numerico da suddividere in bin</li>
<li><code>breaks</code> è un vettore contenente i valori di taglio, ovvero i punti di separazione tra i bin. Questo può essere specificato in diversi modi, ad esempio tramite un numero intero che specifica il numero di bin desiderati o un vettore numerico che specifica i limiti di ogni bin.</li>
<li><code>labels</code> è un vettore di etichette per ogni bin. Se non specificato, gli intervalli saranno etichettati in base ai loro limiti.</li>
<li><code>include.lowest</code> indica se includere o meno il valore più basso del vettore x nel primo bin. Il valore predefinito è FALSE.</li>
<li><code>right</code> indica se i bin devono essere chiusi a destra o a sinistra. Il valore predefinito è TRUE, ovvero i bin sono chiusi a destra.</li>
<li><code>dig.lab</code> è il numero di cifre decimali da utilizzare per le etichette, se specificato.</li>
<li><code>...</code> sono altri argomenti opzionali.</li>
</ul>
</div>
</div>
<p>Ecco un esempio di utilizzo della funzione <code>cut()</code> per suddividere <code>str</code> in tre bin di uguale ampiezza:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>str_cat3 <span class="ot">&lt;-</span> <span class="fu">cut</span>(Caschool<span class="sc">$</span>str, <span class="dv">3</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(str_cat3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (14,17.9] (17.9,21.9] (21.9,25.8] 
         73         305          42 </code></pre>
</div>
</div>
<p>In questo caso il comando <code>summary</code> produce una tavola di frequenza con il numero delle scuole in ciascuna delle tre categorie (14,17.9], (17.9,21.9], (21.9,25.8].</p>
<p>Possiamo anche specificare i <code>breaks</code> in modo esplicito</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>str_cat3 <span class="ot">&lt;-</span> <span class="fu">cut</span>(Caschool<span class="sc">$</span>str, <span class="fu">c</span>(<span class="dv">13</span>,<span class="dv">20</span>, <span class="dv">21</span>, <span class="dv">26</span>))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(str_cat3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(13,20] (20,21] (21,26] 
    243      86      91 </code></pre>
</div>
</div>
<p>In questo ultimo caso, gli intervalli sono (13,20], (20,21], (21,26].</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>str_cat3</code> e, in generale, l’output di <code>cut</code> è un oggetto di classe <code>factor</code>. Questo tipo di variabili sono utilizzate per rappresentare variabili categoriche o qualitative, ovvero variabili che possono assumere un numero limitato di categorie o livelli (come il numero di intervalli nel nostro questo caso). La funzione <code>summary()</code> restituisce una tavola di frequenza per questo tipo di variabili perchè non avrebbe senso calcolare media, mediana e le altre quantità che sono solitamente restituita da <code>summary</code> quando l’argomento è una variabile di tipo <code>numeric</code>.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-19"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-19-1"><a href="#annotated-cell-19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="annotated-cell-19-2"><a href="#annotated-cell-19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-19-3"><a href="#annotated-cell-19-3" aria-hidden="true" tabindex="-1"></a>df_2 <span class="ot">&lt;-</span> Caschool <span class="sc">|&gt;</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-19" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-19-4" class="code-annotation-target"><a href="#annotated-cell-19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">str_cat =</span> <span class="fu">cut</span>(str, <span class="dv">25</span>)) <span class="sc">|&gt;</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-19" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-19-5" class="code-annotation-target"><a href="#annotated-cell-19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(str_cat) <span class="sc">|&gt;</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-19" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-19-6" class="code-annotation-target"><a href="#annotated-cell-19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">m =</span> <span class="fu">mean</span>(testscr), <span class="at">s =</span> <span class="fu">sd</span>(testscr), <span class="at">n =</span> <span class="fu">n</span>())</span>
<span id="annotated-cell-19-7"><a href="#annotated-cell-19-7" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-19" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-19-8" class="code-annotation-target"><a href="#annotated-cell-19-8" aria-hidden="true" tabindex="-1"></a>df_2 <span class="sc">|&gt;</span> <span class="fu">kable</span>()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-19" data-target-annotation="1">1</dt>
<dd>
<span data-code-lines="4" data-code-cell="annotated-cell-19" data-code-annotation="1">la funzione <code>cut</code> per dividere <code>str</code> in <code>25</code> intervalli;</span>
</dd>
<dt data-target-cell="annotated-cell-19" data-target-annotation="2">2</dt>
<dd>
<span data-code-lines="5" data-code-cell="annotated-cell-19" data-code-annotation="2"><code>group_by</code> suddivide <code>Caschool</code> in gruppi specificati da <code>str_cat</code></span>
</dd>
<dt data-target-cell="annotated-cell-19" data-target-annotation="3">3</dt>
<dd>
<span data-code-lines="6" data-code-cell="annotated-cell-19" data-code-annotation="3"><code>summarize</code> calcola la media, la standard deviation e il numero di osservazioni per ciascun gruppo</span>
</dd>
<dt data-target-cell="annotated-cell-19" data-target-annotation="4">4</dt>
<dd>
<span data-code-lines="8" data-code-cell="annotated-cell-19" data-code-annotation="4"><code>kabble</code> restituisce la tavole dei valori</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">str_cat</th>
<th style="text-align: right;">m</th>
<th style="text-align: right;">s</th>
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(14,14.5]</td>
<td style="text-align: right;">646.0500</td>
<td style="text-align: right;">14.778549</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">(14.5,14.9]</td>
<td style="text-align: right;">681.0750</td>
<td style="text-align: right;">20.117197</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(14.9,15.4]</td>
<td style="text-align: right;">669.0583</td>
<td style="text-align: right;">27.490814</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">(15.4,15.9]</td>
<td style="text-align: right;">666.4300</td>
<td style="text-align: right;">16.397313</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(15.9,16.4]</td>
<td style="text-align: right;">657.4625</td>
<td style="text-align: right;">31.451677</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">(16.4,16.8]</td>
<td style="text-align: right;">656.4000</td>
<td style="text-align: right;">22.941905</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(16.8,17.3]</td>
<td style="text-align: right;">655.1200</td>
<td style="text-align: right;">19.810342</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">(17.3,17.8]</td>
<td style="text-align: right;">661.8417</td>
<td style="text-align: right;">21.060798</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(17.8,18.2]</td>
<td style="text-align: right;">660.9820</td>
<td style="text-align: right;">21.377905</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">(18.2,18.7]</td>
<td style="text-align: right;">655.2611</td>
<td style="text-align: right;">19.005516</td>
<td style="text-align: right;">27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(18.7,19.2]</td>
<td style="text-align: right;">659.1279</td>
<td style="text-align: right;">17.430926</td>
<td style="text-align: right;">43</td>
</tr>
<tr class="even">
<td style="text-align: left;">(19.2,19.7]</td>
<td style="text-align: right;">654.1674</td>
<td style="text-align: right;">18.195814</td>
<td style="text-align: right;">46</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(19.7,20.1]</td>
<td style="text-align: right;">652.2074</td>
<td style="text-align: right;">16.740564</td>
<td style="text-align: right;">54</td>
</tr>
<tr class="even">
<td style="text-align: left;">(20.1,20.6]</td>
<td style="text-align: right;">652.5538</td>
<td style="text-align: right;">18.840601</td>
<td style="text-align: right;">39</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(20.6,21.1]</td>
<td style="text-align: right;">650.9581</td>
<td style="text-align: right;">18.103751</td>
<td style="text-align: right;">37</td>
</tr>
<tr class="even">
<td style="text-align: left;">(21.1,21.6]</td>
<td style="text-align: right;">645.9219</td>
<td style="text-align: right;">17.020841</td>
<td style="text-align: right;">32</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(21.6,22]</td>
<td style="text-align: right;">651.4000</td>
<td style="text-align: right;">19.099852</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="even">
<td style="text-align: left;">(22,22.5]</td>
<td style="text-align: right;">650.9208</td>
<td style="text-align: right;">14.543992</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(22.5,23]</td>
<td style="text-align: right;">639.0750</td>
<td style="text-align: right;">16.285659</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">(23,23.4]</td>
<td style="text-align: right;">643.8833</td>
<td style="text-align: right;">17.057669</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(23.4,23.9]</td>
<td style="text-align: right;">658.9750</td>
<td style="text-align: right;">7.672091</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">(23.9,24.4]</td>
<td style="text-align: right;">676.8500</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(24.4,24.9]</td>
<td style="text-align: right;">651.2000</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">(24.9,25.3]</td>
<td style="text-align: right;">642.3833</td>
<td style="text-align: right;">23.492216</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(25.3,25.8]</td>
<td style="text-align: right;">659.5750</td>
<td style="text-align: right;">7.601398</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Alcuni degli errori standard sono uguali a <code>NA</code> perché in almeno uno dei gruppi il numero di osservazioni è inferiore a 2, il numero minimo per poter calcolare una misura dispersione.</p>
<p>Manipolando <code>df_2</code>, possiamo calcolare le differenze nelle media campionarie fra due intervalli adiacenti.</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-20"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><a class="code-annotation-anchor" data-target-cell="annotated-cell-20" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-20-1" class="code-annotation-target"><a href="#annotated-cell-20-1" aria-hidden="true" tabindex="-1"></a>df_3 <span class="ot">&lt;-</span> df_2 <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">Delta_str =</span> <span class="fu">paste0</span>(str_cat, <span class="st">"-"</span>, <span class="fu">lag</span>(str_cat)),</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-20" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-20-2" class="code-annotation-target"><a href="#annotated-cell-20-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">Delta_testscr =</span> m <span class="sc">-</span> <span class="fu">lag</span>(m),</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-20" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-20-3" class="code-annotation-target"><a href="#annotated-cell-20-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">stderr =</span> <span class="fu">sqrt</span>(s<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n <span class="sc">+</span> <span class="fu">lag</span>(s<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>n))) <span class="sc">|&gt;</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-20" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-20-4" class="code-annotation-target"><a href="#annotated-cell-20-4" aria-hidden="true" tabindex="-1"></a>               <span class="fu">select</span>(Delta_str, Delta_testscr, stderr)</span>
<span id="annotated-cell-20-5"><a href="#annotated-cell-20-5" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-20" data-target-annotation="5" onclick="event.preventDefault();">5</a><span id="annotated-cell-20-6" class="code-annotation-target"><a href="#annotated-cell-20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(df_3)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-20" data-target-annotation="1">1</dt>
<dd>
<span data-code-lines="1" data-code-cell="annotated-cell-20" data-code-annotation="1">la variabile <code>Delta_str</code> è uguale alla differenza dei due intervalli ottenuta incollando <code>paste0</code> l’intervallo di ciascuna riga con quella precedente (la funzione <code>lag(m)</code> associa il valore di <code>m</code> della riga precedente). Questa variabile è utile per annotare l’asse delle ascisse del grafico che produrremo prodotto in seguito.</span>
</dd>
<dt data-target-cell="annotated-cell-20" data-target-annotation="2">2</dt>
<dd>
<span data-code-lines="2" data-code-cell="annotated-cell-20" data-code-annotation="2"><code>Delta_str</code> contiene la differenze delle medie campionari di due intervalli successivi. Queste differenze sono calcolate usando <code>m - lag(m)</code> e quindi <code>Delta_testscr</code> è uguale a <code>m</code>, la media per l’intervallo, meno il valore della media per l’intervallo che preceda la riga in considerazione (<code>lag(m)</code>)</span>
</dd>
<dt data-target-cell="annotated-cell-20" data-target-annotation="3">3</dt>
<dd>
<span data-code-lines="3" data-code-cell="annotated-cell-20" data-code-annotation="3"><code>stderr</code> è l’errore standard della differenza delle medie in ciascun intervallo che è uguale a</span>
</dd>
<dt data-target-cell="annotated-cell-20" data-target-annotation="4">4</dt>
<dd>
<span data-code-lines="4" data-code-cell="annotated-cell-20" data-code-annotation="4">selezioniamo le variabili che ci servono per il grafico mediante la funzione <code>select()</code></span>
</dd>
<dt data-target-cell="annotated-cell-20" data-target-annotation="5">5</dt>
<dd>
<span data-code-lines="6" data-code-cell="annotated-cell-20" data-code-annotation="5"><code>kable(df_3)</code> formatta il <code>data.frame</code> come una tavolo <code>html</code>. La funzione <code>kable</code> è contenuta nel pacchetto <code>knitr</code>.</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Delta_str</th>
<th style="text-align: right;">Delta_testscr</th>
<th style="text-align: right;">stderr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(14,14.5]-NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">(14.5,14.9]-(14,14.5]</td>
<td style="text-align: right;">35.0249939</td>
<td style="text-align: right;">17.650880</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(14.9,15.4]-(14.5,14.9]</td>
<td style="text-align: right;">-12.0166524</td>
<td style="text-align: right;">18.119279</td>
</tr>
<tr class="even">
<td style="text-align: left;">(15.4,15.9]-(14.9,15.4]</td>
<td style="text-align: right;">-2.6283122</td>
<td style="text-align: right;">13.406411</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(15.9,16.4]-(15.4,15.9]</td>
<td style="text-align: right;">-8.9675232</td>
<td style="text-align: right;">17.351552</td>
</tr>
<tr class="even">
<td style="text-align: left;">(16.4,16.8]-(15.9,16.4]</td>
<td style="text-align: right;">-1.0624949</td>
<td style="text-align: right;">17.063496</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(16.8,17.3]-(16.4,16.8]</td>
<td style="text-align: right;">-1.2799978</td>
<td style="text-align: right;">9.116243</td>
</tr>
<tr class="even">
<td style="text-align: left;">(17.3,17.8]-(16.8,17.3]</td>
<td style="text-align: right;">6.7216634</td>
<td style="text-align: right;">7.597797</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(17.8,18.2]-(17.3,17.8]</td>
<td style="text-align: right;">-0.8596676</td>
<td style="text-align: right;">6.063179</td>
</tr>
<tr class="even">
<td style="text-align: left;">(18.2,18.7]-(17.8,18.2]</td>
<td style="text-align: right;">-5.7208842</td>
<td style="text-align: right;">5.626609</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(18.7,19.2]-(18.2,18.7]</td>
<td style="text-align: right;">3.8667941</td>
<td style="text-align: right;">4.521517</td>
</tr>
<tr class="even">
<td style="text-align: left;">(19.2,19.7]-(18.7,19.2]</td>
<td style="text-align: right;">-4.9605207</td>
<td style="text-align: right;">3.776710</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(19.7,20.1]-(19.2,19.7]</td>
<td style="text-align: right;">-1.9599775</td>
<td style="text-align: right;">3.519561</td>
</tr>
<tr class="even">
<td style="text-align: left;">(20.1,20.6]-(19.7,20.1]</td>
<td style="text-align: right;">0.3464399</td>
<td style="text-align: right;">3.780410</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(20.6,21.1]-(20.1,20.6]</td>
<td style="text-align: right;">-1.5957303</td>
<td style="text-align: right;">4.237894</td>
</tr>
<tr class="even">
<td style="text-align: left;">(21.1,21.6]-(20.6,21.1]</td>
<td style="text-align: right;">-5.0362433</td>
<td style="text-align: right;">4.232187</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(21.6,22]-(21.1,21.6]</td>
<td style="text-align: right;">5.4781291</td>
<td style="text-align: right;">5.776997</td>
</tr>
<tr class="even">
<td style="text-align: left;">(22,22.5]-(21.6,22]</td>
<td style="text-align: right;">-0.4791768</td>
<td style="text-align: right;">6.476697</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(22.5,23]-(22,22.5]</td>
<td style="text-align: right;">-11.8458333</td>
<td style="text-align: right;">6.644515</td>
</tr>
<tr class="even">
<td style="text-align: left;">(23,23.4]-(22.5,23]</td>
<td style="text-align: right;">4.8083476</td>
<td style="text-align: right;">8.661194</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(23.4,23.9]-(23,23.4]</td>
<td style="text-align: right;">15.0916951</td>
<td style="text-align: right;">8.827486</td>
</tr>
<tr class="even">
<td style="text-align: left;">(23.9,24.4]-(23.4,23.9]</td>
<td style="text-align: right;">17.8749390</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(24.4,24.9]-(23.9,24.4]</td>
<td style="text-align: right;">-25.6499634</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">(24.9,25.3]-(24.4,24.9]</td>
<td style="text-align: right;">-8.8166707</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(25.3,25.8]-(24.9,25.3]</td>
<td style="text-align: right;">17.1916097</td>
<td style="text-align: right;">14.589449</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Si noti che per prima riga la differenza delle medie è <code>NA</code>. Il motivo è che non c’è un intervallo con valori più piccoli di per poter calcolare la differenza. La seconda riga ci dice che <span class="math display">\[
\overline{testscr}_{str \in (14.5,14.9]} - \overline{testscr}_{str \in (14,14.5]}  = 35.0249939,
\]</span> e che quindi scuole con classi con <span class="math inline">\((14.5,14.9]\)</span> studenti per insegnante hanno punteggi più alti di circa 35.0249939 punti rispetto a quelle con <span class="math inline">\(str\in (14,14.5]\)</span>. Questo valore positivo (classi più piccole hanno test score più bassi) e molto grande (quasi due volte la deviazione standard dei punteggi in tutto il campione) è dovuto al fatto che stiamo stimando la differenza dei valori attesi usando soltanto 4 scuole. Un numero troppo esigue per aspettarci che la stima sia in qualche modo “vicina” a quella che potremmo stimare se avessimo a disposizione i dati nel campione.</p>
<p>La terza riga ci dice che <span class="math display">\[
\overline{testscr}_{str \in (14.9,15.4]} - \overline{testscr}_{str \in (14.5,14.9]}  = -12.0166524,
\]</span> e che quindi scuole con <span class="math inline">\(str\in (14.9,15.4]\)</span> hanno punteggi più alti di circa -12.0166524 punti rispetto a quelle con <span class="math inline">\(str\in (14.5,14.9]\)</span>. E così via per le altre righe.</p>
<p>E’ molto probabile che tutte le stime e non soltanto quelle della prima riga siano particolarmente imprecise visto che sono tutte basate su un numero esiguo di osservazioni. Per quantificare la loro precisione, o la loro imprecisione, possiamo costruire l’intervallo di confidenza (al 95%) per ciascun valore dell’intervallo di <span class="math inline">\(str\)</span>. L’intervallo di confidenza al 95% è:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(df_3<span class="sc">$</span>Delta_testscr <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> df_3<span class="sc">$</span>stderr,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  df_3<span class="sc">$</span>Delta_testscr <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> df_3<span class="sc">$</span>stderr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>dove <code>stderr</code> è l’errore standard della differenza delle media che è stato calcolato nel precdedente blocco di codice.</p>
<p>Per aggiungere l’intervallo di confidenza a <code>df_3</code> possiamo usare <code>dplyr</code> e la funzione <code>mutate</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-22"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-22-1"><a href="#annotated-cell-22-1" aria-hidden="true" tabindex="-1"></a>df_3 <span class="ot">&lt;-</span> df_3 <span class="sc">|&gt;</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-22" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-22-2" class="code-annotation-target"><a href="#annotated-cell-22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ci_sx =</span> Delta_testscr <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> stderr,</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-22" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-22-3" class="code-annotation-target"><a href="#annotated-cell-22-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ci_dx =</span> Delta_testscr <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> stderr)</span>
<span id="annotated-cell-22-4"><a href="#annotated-cell-22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-22-5"><a href="#annotated-cell-22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(df_3)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-22" data-target-annotation="1">1</dt>
<dd>
<span data-code-lines="2" data-code-cell="annotated-cell-22" data-code-annotation="1">l’estremo sinistro dell’intervallo di confidenza;</span>
</dd>
<dt data-target-cell="annotated-cell-22" data-target-annotation="2">2</dt>
<dd>
<span data-code-lines="3" data-code-cell="annotated-cell-22" data-code-annotation="2">l’estremo destro dell’intervallo di confidenza;</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 34%">
<col style="width: 20%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Delta_str</th>
<th style="text-align: right;">Delta_testscr</th>
<th style="text-align: right;">stderr</th>
<th style="text-align: right;">ci_sx</th>
<th style="text-align: right;">ci_dx</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(14,14.5]-NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">(14.5,14.9]-(14,14.5]</td>
<td style="text-align: right;">35.0249939</td>
<td style="text-align: right;">17.650880</td>
<td style="text-align: right;">0.4292697</td>
<td style="text-align: right;">69.620718</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(14.9,15.4]-(14.5,14.9]</td>
<td style="text-align: right;">-12.0166524</td>
<td style="text-align: right;">18.119279</td>
<td style="text-align: right;">-47.5304392</td>
<td style="text-align: right;">23.497134</td>
</tr>
<tr class="even">
<td style="text-align: left;">(15.4,15.9]-(14.9,15.4]</td>
<td style="text-align: right;">-2.6283122</td>
<td style="text-align: right;">13.406411</td>
<td style="text-align: right;">-28.9048769</td>
<td style="text-align: right;">23.648253</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(15.9,16.4]-(15.4,15.9]</td>
<td style="text-align: right;">-8.9675232</td>
<td style="text-align: right;">17.351552</td>
<td style="text-align: right;">-42.9765654</td>
<td style="text-align: right;">25.041519</td>
</tr>
<tr class="even">
<td style="text-align: left;">(16.4,16.8]-(15.9,16.4]</td>
<td style="text-align: right;">-1.0624949</td>
<td style="text-align: right;">17.063496</td>
<td style="text-align: right;">-34.5069476</td>
<td style="text-align: right;">32.381958</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(16.8,17.3]-(16.4,16.8]</td>
<td style="text-align: right;">-1.2799978</td>
<td style="text-align: right;">9.116243</td>
<td style="text-align: right;">-19.1478335</td>
<td style="text-align: right;">16.587838</td>
</tr>
<tr class="even">
<td style="text-align: left;">(17.3,17.8]-(16.8,17.3]</td>
<td style="text-align: right;">6.7216634</td>
<td style="text-align: right;">7.597797</td>
<td style="text-align: right;">-8.1700183</td>
<td style="text-align: right;">21.613345</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(17.8,18.2]-(17.3,17.8]</td>
<td style="text-align: right;">-0.8596676</td>
<td style="text-align: right;">6.063179</td>
<td style="text-align: right;">-12.7434989</td>
<td style="text-align: right;">11.024164</td>
</tr>
<tr class="even">
<td style="text-align: left;">(18.2,18.7]-(17.8,18.2]</td>
<td style="text-align: right;">-5.7208842</td>
<td style="text-align: right;">5.626609</td>
<td style="text-align: right;">-16.7490376</td>
<td style="text-align: right;">5.307269</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(18.7,19.2]-(18.2,18.7]</td>
<td style="text-align: right;">3.8667941</td>
<td style="text-align: right;">4.521517</td>
<td style="text-align: right;">-4.9953794</td>
<td style="text-align: right;">12.728967</td>
</tr>
<tr class="even">
<td style="text-align: left;">(19.2,19.7]-(18.7,19.2]</td>
<td style="text-align: right;">-4.9605207</td>
<td style="text-align: right;">3.776710</td>
<td style="text-align: right;">-12.3628722</td>
<td style="text-align: right;">2.441831</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(19.7,20.1]-(19.2,19.7]</td>
<td style="text-align: right;">-1.9599775</td>
<td style="text-align: right;">3.519561</td>
<td style="text-align: right;">-8.8583162</td>
<td style="text-align: right;">4.938361</td>
</tr>
<tr class="even">
<td style="text-align: left;">(20.1,20.6]-(19.7,20.1]</td>
<td style="text-align: right;">0.3464399</td>
<td style="text-align: right;">3.780410</td>
<td style="text-align: right;">-7.0631635</td>
<td style="text-align: right;">7.756043</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(20.6,21.1]-(20.1,20.6]</td>
<td style="text-align: right;">-1.5957303</td>
<td style="text-align: right;">4.237894</td>
<td style="text-align: right;">-9.9020023</td>
<td style="text-align: right;">6.710542</td>
</tr>
<tr class="even">
<td style="text-align: left;">(21.1,21.6]-(20.6,21.1]</td>
<td style="text-align: right;">-5.0362433</td>
<td style="text-align: right;">4.232187</td>
<td style="text-align: right;">-13.3313288</td>
<td style="text-align: right;">3.258842</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(21.6,22]-(21.1,21.6]</td>
<td style="text-align: right;">5.4781291</td>
<td style="text-align: right;">5.776997</td>
<td style="text-align: right;">-5.8447856</td>
<td style="text-align: right;">16.801044</td>
</tr>
<tr class="even">
<td style="text-align: left;">(22,22.5]-(21.6,22]</td>
<td style="text-align: right;">-0.4791768</td>
<td style="text-align: right;">6.476697</td>
<td style="text-align: right;">-13.1735022</td>
<td style="text-align: right;">12.215148</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(22.5,23]-(22,22.5]</td>
<td style="text-align: right;">-11.8458333</td>
<td style="text-align: right;">6.644515</td>
<td style="text-align: right;">-24.8690823</td>
<td style="text-align: right;">1.177416</td>
</tr>
<tr class="even">
<td style="text-align: left;">(23,23.4]-(22.5,23]</td>
<td style="text-align: right;">4.8083476</td>
<td style="text-align: right;">8.661194</td>
<td style="text-align: right;">-12.1675926</td>
<td style="text-align: right;">21.784288</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(23.4,23.9]-(23,23.4]</td>
<td style="text-align: right;">15.0916951</td>
<td style="text-align: right;">8.827486</td>
<td style="text-align: right;">-2.2101770</td>
<td style="text-align: right;">32.393567</td>
</tr>
<tr class="even">
<td style="text-align: left;">(23.9,24.4]-(23.4,23.9]</td>
<td style="text-align: right;">17.8749390</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(24.4,24.9]-(23.9,24.4]</td>
<td style="text-align: right;">-25.6499634</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">(24.9,25.3]-(24.4,24.9]</td>
<td style="text-align: right;">-8.8166707</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(25.3,25.8]-(24.9,25.3]</td>
<td style="text-align: right;">17.1916097</td>
<td style="text-align: right;">14.589449</td>
<td style="text-align: right;">-11.4037108</td>
<td style="text-align: right;">45.786930</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Come si vede chiaramente dall’analisi della tabella, tutti gli intervalli di confidenza sono molto ampi. Come preannunciato, i dati a nostra disposizione non sono abbastanza informativi per poter stimare tutte le differenze su intervalli così poco numerosi. Anche nel caso in cui considerassimo la differenza delle medie in scuole con <span class="math inline">\(str\in(18.7,19.2]\)</span> (27 scuole) e scuole con <span class="math inline">\(str\in (18.2,18.7]\)</span> (47 scuole), l’intervallo di confidenza è molto ampio: <span class="math inline">\((-4.9953794, 12.7289675)\)</span>. Un intervallo di confidenza così ampio implica che non possiamo neanche quantificare con l’appropriata confidenza il segno della differenza che potrebbe essere -12 o 2.</p>
<p>La rappresentazione grafica delle informazioni contenute in una tavole facilita spesso la comprensione dei risultati.</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-23"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><a class="code-annotation-anchor" data-target-cell="annotated-cell-23" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-23-1" class="code-annotation-target"><a href="#annotated-cell-23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_3, <span class="fu">aes</span>(<span class="at">x=</span>Delta_str,<span class="at">y=</span>Delta_testscr)) <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-23" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-23-2" class="code-annotation-target"><a href="#annotated-cell-23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>ci_sx, <span class="at">ymax=</span>ci_dx)) <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-23" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-23-3" class="code-annotation-target"><a href="#annotated-cell-23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"darkred"</span>) <span class="sc">+</span></span>
<span id="annotated-cell-23-4"><a href="#annotated-cell-23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="annotated-cell-23-5"><a href="#annotated-cell-23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Intervalli str"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Delta Media testscr"</span>) <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-23" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-23-6" class="code-annotation-target"><a href="#annotated-cell-23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>))</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-23" data-target-annotation="1">1</dt>
<dd>
<span data-code-lines="1" data-code-cell="annotated-cell-23" data-code-annotation="1">sull’ascissa abbiamo la differenza degli intervalli, sull’ordinata la differenza delle medie;</span>
</dd>
<dt data-target-cell="annotated-cell-23" data-target-annotation="2">2</dt>
<dd>
<span data-code-lines="2" data-code-cell="annotated-cell-23" data-code-annotation="2">la geometria utilizzata è <code>geom_pointrange</code>, che “plotta” la differenza delle medie (il punto) e l’intervallo di confidenza al 95% definito da (<code>(ci_sx, ci_dx)</code>) e rappresentato dalle linee che si estendono verticalmente.</span>
</dd>
<dt data-target-cell="annotated-cell-23" data-target-annotation="3">3</dt>
<dd>
<span data-code-lines="3" data-code-cell="annotated-cell-23" data-code-annotation="3"><code>geom_hline(yintercept=0, col = "darkred")</code> produce una riga orizzonate di colore rosso scuro</span>
</dd>
<dt data-target-cell="annotated-cell-23" data-target-annotation="4">4</dt>
<dd>
<span data-code-lines="6" data-code-cell="annotated-cell-23" data-code-annotation="4">le etichette dell’asse della x sono ruotate di 90 gradi per favorire la loro leggibilità.</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<p><img src="IntroduzioneR_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Il grafico mostra che:</p>
<ol type="1">
<li>La stima di molte delle differenze è negativa</li>
<li>Tutti gli intervalli di confidenza sono troppo ampi per poter concludere con l’appropriata confidenza che il valore della differenza nella popolazione è di uno specifico segno</li>
<li>In tre casi non è possibile costruire l’intervallo di confidenza.</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>