<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Econometria 2023/2024 - Giuseppe Ragusa - Sapienza">

<title>Econometria - Variabili Strumentali</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href=".//files/icon-512.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Econometria</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./materiale.html"> 
<span class="menu-text">Materiale didattico</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./IntroduzioneR.html">R</a></li><li class="breadcrumb-item"><a href="./IVapp.html">Variabili strumentali</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Slides</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lezione1-2.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-slides" role="img">
</i> 
 <span class="menu-text">Lezione 1&amp;2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lezione34.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-slides" role="img">
</i> 
 <span class="menu-text">Lezione 3&amp;4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lezione67.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-slides" role="img">
</i> 
 <span class="menu-text">Lezione 6&amp;7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lezione8.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-slides" role="img">
</i> 
 <span class="menu-text">Lezione 8</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lezione9.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-slides" role="img">
</i> 
 <span class="menu-text">Lezione 9</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lezione10.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-slides" role="img">
</i> 
 <span class="menu-text">Lezione 10</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lezione11.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-slides" role="img">
</i> 
 <span class="menu-text">Lezione 11</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lezione12.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-slides" role="img">
</i> 
 <span class="menu-text">Lezione 12</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lezione14.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-slides" role="img">
</i> 
 <span class="menu-text">Lezione 14</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IntroduzioneR.html" class="sidebar-item-text sidebar-link"><i class="bi bi-filetype-html" role="img">
</i> 
 <span class="menu-text">Introduzione a <code>R</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Dummy_ilfs.html" class="sidebar-item-text sidebar-link"><i class="bi bi-filetype-html" role="img">
</i> 
 <span class="menu-text">Variabili dummy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probmodel_app.html" class="sidebar-item-text sidebar-link"><i class="bi bi-filetype-html" role="img">
</i> 
 <span class="menu-text">Modelli per probabilità</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./panel_app.html" class="sidebar-item-text sidebar-link"><i class="bi bi-filetype-html" role="img">
</i> 
 <span class="menu-text">Panel data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IVapp.html" class="sidebar-item-text sidebar-link active"><i class="bi bi-filetype-html" role="img">
</i> 
 <span class="menu-text">Variabili strumentali</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Materiale Esami</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mock_exam.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-vials" role="img">
</i> 
 <span class="menu-text">Esempio domand esame (I)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://elearning.uniroma1.it/pluginfile.php/1273719/mod_resource/content/1/mockexam.pdf" class="sidebar-item-text sidebar-link"><i class="bi bi-vials" role="img">
</i> 
 <span class="menu-text">Esempio domand esame (II)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://elearning.uniroma1.it/mod/quiz/view.php?id=610929" class="sidebar-item-text sidebar-link"><i class="bi bi-vials" role="img">
</i> 
 <span class="menu-text">Simulazione esame (moodle)</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#ritorni-di-educazione" id="toc-ritorni-di-educazione" class="nav-link active" data-scroll-target="#ritorni-di-educazione">Ritorni di educazione</a></li>
  <li><a href="#descrizione-del-dataset-card" id="toc-descrizione-del-dataset-card" class="nav-link" data-scroll-target="#descrizione-del-dataset-card">Descrizione del Dataset <code>card</code></a></li>
  <li><a href="#stima-ols-di-base" id="toc-stima-ols-di-base" class="nav-link" data-scroll-target="#stima-ols-di-base">Stima OLS di Base</a></li>
  <li><a href="#modello-ols-con-variabili-esogene" id="toc-modello-ols-con-variabili-esogene" class="nav-link" data-scroll-target="#modello-ols-con-variabili-esogene">Modello OLS con variabili esogene</a>
  <ul class="collapse">
  <li><a href="#giustificazione-della-validità-degli-strumenti" id="toc-giustificazione-della-validità-degli-strumenti" class="nav-link" data-scroll-target="#giustificazione-della-validità-degli-strumenti">Giustificazione della validità degli strumenti</a></li>
  </ul></li>
  <li><a href="#rilevanza" id="toc-rilevanza" class="nav-link" data-scroll-target="#rilevanza">Rilevanza</a></li>
  <li><a href="#secondo-stadio-della-regressione-iv" id="toc-secondo-stadio-della-regressione-iv" class="nav-link" data-scroll-target="#secondo-stadio-della-regressione-iv">Secondo Stadio della Regressione IV</a></li>
  <li><a href="#test-per-endogeneità" id="toc-test-per-endogeneità" class="nav-link" data-scroll-target="#test-per-endogeneità">Test per endogeneità</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./IntroduzioneR.html">R</a></li><li class="breadcrumb-item"><a href="./IVapp.html">Variabili strumentali</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Variabili Strumentali</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="ritorni-di-educazione" class="level2">
<h2 class="anchored" data-anchor-id="ritorni-di-educazione">Ritorni di educazione</h2>
<p>Una stima precisa dell’effetto dell’educazione sui salari è importante sia a livello individuale che sociale. A livello individuale, comprendere il ritorno sull’investimento in istruzione aiuta le persone a fare scelte informate riguardo al loro percorso educativo. Questo è particolarmente rilevante in contesti in cui l’educazione rappresenta un investimento significativo di tempo e risorse finanziarie. A livello sociale, una stima precisa degli effetti dell’educazione sui salari fornisce ai policymaker un’informazione cruciale per formulare politiche di efficaci. Ad esempio, politiche che mirano a incrementare l’accesso all’istruzione superiore potrebbero essere giustificate da un alto ritorno economico dell’educazione, il che a sua volta può stimolare la crescita economica, ridurre la disuguaglianza e promuovere una maggiore coesione sociale.</p>
</section>
<section id="descrizione-del-dataset-card" class="level2">
<h2 class="anchored" data-anchor-id="descrizione-del-dataset-card">Descrizione del Dataset <code>card</code></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(wooldridge)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(card)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#echo: false</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(formattable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Il dataset <code>card</code> include una serie di variabili relative alle caratteristiche demografiche degli individui, come età, genere, il livello di istruzione raggiunto, l’esperienza lavorativa, e altri fattori che possono influenzare i salari. Useremo questo dataset per applicare la tecnica delle variabili strumentali per progvare ad isolare l’effetto dell’istruzione dalle distorsioni dovute a variabili omesse.</p>
<p>La <strong>?@tbl-descrizione</strong> contiene una descrizione dettagliata delle variabile contenute nel dataset. La <a href="#tbl-summary" class="quarto-xref">Table&nbsp;1</a> contiene invece la statistiche descrittive.</p>
<table class="table">
<colgroup>
<col style="width: 24%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Variabile</th>
<th>Descrizione</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>id</code></td>
<td>Identificativo unico per ciascun individuo</td>
</tr>
<tr class="even">
<td><code>nearc2</code></td>
<td>(1/0) se vicino a un college a 2 anni</td>
</tr>
<tr class="odd">
<td><code>nearc4</code></td>
<td>(1/0) se vicino a un college a 4 anni</td>
</tr>
<tr class="even">
<td><code>educ</code></td>
<td>Anni di educazione completati</td>
</tr>
<tr class="odd">
<td><code>age</code></td>
<td>Età dell’individuo</td>
</tr>
<tr class="even">
<td><code>fatheduc</code></td>
<td>Anni di educazione completati dal padre</td>
</tr>
<tr class="odd">
<td><code>motheduc</code></td>
<td>Anni di educazione completati dalla madre</td>
</tr>
<tr class="even">
<td><code>weight</code></td>
<td>Peso campionario</td>
</tr>
<tr class="odd">
<td><code>momdad14</code></td>
<td>(1/0) se viveva con entrambi i genitori a 14 anni</td>
</tr>
<tr class="even">
<td><code>sinmom14</code></td>
<td>(1/0) se viveva solo con la madre a 14 anni</td>
</tr>
<tr class="odd">
<td><code>step14</code></td>
<td>(1/0) se viveva con un genitore acquisito a 14 anni</td>
</tr>
<tr class="even">
<td><code>black</code></td>
<td>(1/0) se l’individuo è di razza nera</td>
</tr>
<tr class="odd">
<td><code>smsa</code></td>
<td>(1/0) se residente in un’area metropolitana</td>
</tr>
<tr class="even">
<td><code>south</code></td>
<td>(1/0) se residente nel sud degli USA</td>
</tr>
<tr class="odd">
<td><code>wage</code></td>
<td>Salario annuo</td>
</tr>
<tr class="even">
<td><code>enroll</code></td>
<td>(1/0) di iscrizione a scuola nel 1966</td>
</tr>
<tr class="odd">
<td><code>KWW</code></td>
<td>Punteggio sul test di conoscenza del mondo del lavoro</td>
</tr>
<tr class="even">
<td><code>IQ</code></td>
<td>Quoziente intellettivo</td>
</tr>
<tr class="odd">
<td><code>married</code></td>
<td>(1/0) dello stato civile (sposato)</td>
</tr>
<tr class="even">
<td><code>exper</code></td>
<td>Anni di esperienza lavorativa</td>
</tr>
<tr class="odd">
<td><code>lwage</code></td>
<td>Logaritmo naturale del salario</td>
</tr>
<tr class="even">
<td><code>expersq</code></td>
<td>Esperienza lavorativa al quadrato</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"gtsummary"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>card <span class="sc">|&gt;</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tbl_summary</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="fu">list</span>(</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">all_continuous</span>() <span class="sc">~</span> <span class="st">"{mean} ({sd})"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">all_categorical</span>() <span class="sc">~</span> <span class="st">"{n} ({p}%)"</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="fu">all_continuous</span>() <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing_text =</span> <span class="st">"(Osservazioni mancanti)"</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="co">#include = names(Hmda)</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">modify_header</span>(<span class="at">label =</span> <span class="st">"**Variabili**"</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bold_labels</span>() <span class="co">#|&gt;</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  <span class="co">#add_n() # add column with total number of non-missing observations</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-summary" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Dataset <code>card</code>: statistiche descrittive.
</figcaption>
<div aria-describedby="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div>
<div id="aaenfmefcb" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#aaenfmefcb table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#aaenfmefcb thead, #aaenfmefcb tbody, #aaenfmefcb tfoot, #aaenfmefcb tr, #aaenfmefcb td, #aaenfmefcb th {
  border-style: none;
}

#aaenfmefcb p {
  margin: 0;
  padding: 0;
}

#aaenfmefcb .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#aaenfmefcb .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#aaenfmefcb .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#aaenfmefcb .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#aaenfmefcb .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#aaenfmefcb .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#aaenfmefcb .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#aaenfmefcb .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#aaenfmefcb .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#aaenfmefcb .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#aaenfmefcb .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#aaenfmefcb .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#aaenfmefcb .gt_spanner_row {
  border-bottom-style: hidden;
}

#aaenfmefcb .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#aaenfmefcb .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#aaenfmefcb .gt_from_md > :first-child {
  margin-top: 0;
}

#aaenfmefcb .gt_from_md > :last-child {
  margin-bottom: 0;
}

#aaenfmefcb .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#aaenfmefcb .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#aaenfmefcb .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#aaenfmefcb .gt_row_group_first td {
  border-top-width: 2px;
}

#aaenfmefcb .gt_row_group_first th {
  border-top-width: 2px;
}

#aaenfmefcb .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#aaenfmefcb .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#aaenfmefcb .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#aaenfmefcb .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#aaenfmefcb .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#aaenfmefcb .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#aaenfmefcb .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#aaenfmefcb .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#aaenfmefcb .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#aaenfmefcb .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#aaenfmefcb .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#aaenfmefcb .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#aaenfmefcb .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#aaenfmefcb .gt_left {
  text-align: left;
}

#aaenfmefcb .gt_center {
  text-align: center;
}

#aaenfmefcb .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#aaenfmefcb .gt_font_normal {
  font-weight: normal;
}

#aaenfmefcb .gt_font_bold {
  font-weight: bold;
}

#aaenfmefcb .gt_font_italic {
  font-style: italic;
}

#aaenfmefcb .gt_super {
  font-size: 65%;
}

#aaenfmefcb .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#aaenfmefcb .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#aaenfmefcb .gt_indent_1 {
  text-indent: 5px;
}

#aaenfmefcb .gt_indent_2 {
  text-indent: 10px;
}

#aaenfmefcb .gt_indent_3 {
  text-indent: 15px;
}

#aaenfmefcb .gt_indent_4 {
  text-indent: 20px;
}

#aaenfmefcb .gt_indent_5 {
  text-indent: 25px;
}
</style>

<table class="gt_table do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header gt_col_headings">
<th id="<strong>Variabili</strong>" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Variabili</strong></th>
<th id="<strong>N = 3,010</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>N = 3,010</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">id</td>
<td class="gt_row gt_center" headers="stat_0">2,581.75 (1,500.54)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">nearc2</td>
<td class="gt_row gt_center" headers="stat_0">1,327 (44%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">nearc4</td>
<td class="gt_row gt_center" headers="stat_0">2,053 (68%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">educ</td>
<td class="gt_row gt_center" headers="stat_0">13.26 (2.68)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">age</td>
<td class="gt_row gt_center" headers="stat_0">28.12 (3.14)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">fatheduc</td>
<td class="gt_row gt_center" headers="stat_0">10.00 (3.72)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;(Osservazioni mancanti)</td>
<td class="gt_row gt_center" headers="stat_0">690</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">motheduc</td>
<td class="gt_row gt_center" headers="stat_0">10.35 (3.18)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;(Osservazioni mancanti)</td>
<td class="gt_row gt_center" headers="stat_0">353</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">weight</td>
<td class="gt_row gt_center" headers="stat_0">321,185.26 (170,645.80)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">momdad14</td>
<td class="gt_row gt_center" headers="stat_0">2,376 (79%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">sinmom14</td>
<td class="gt_row gt_center" headers="stat_0">303 (10%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">step14</td>
<td class="gt_row gt_center" headers="stat_0">117 (3.9%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">reg661</td>
<td class="gt_row gt_center" headers="stat_0">140 (4.7%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">reg662</td>
<td class="gt_row gt_center" headers="stat_0">484 (16%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">reg663</td>
<td class="gt_row gt_center" headers="stat_0">589 (20%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">reg664</td>
<td class="gt_row gt_center" headers="stat_0">193 (6.4%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">reg665</td>
<td class="gt_row gt_center" headers="stat_0">627 (21%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">reg666</td>
<td class="gt_row gt_center" headers="stat_0">289 (9.6%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">reg667</td>
<td class="gt_row gt_center" headers="stat_0">331 (11%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">reg668</td>
<td class="gt_row gt_center" headers="stat_0">85 (2.8%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">reg669</td>
<td class="gt_row gt_center" headers="stat_0">272 (9.0%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">south66</td>
<td class="gt_row gt_center" headers="stat_0">1,247 (41%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">black</td>
<td class="gt_row gt_center" headers="stat_0">703 (23%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">smsa</td>
<td class="gt_row gt_center" headers="stat_0">2,146 (71%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">south</td>
<td class="gt_row gt_center" headers="stat_0">1,215 (40%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">smsa66</td>
<td class="gt_row gt_center" headers="stat_0">1,955 (65%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">wage</td>
<td class="gt_row gt_center" headers="stat_0">577.28 (262.96)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">enroll</td>
<td class="gt_row gt_center" headers="stat_0">278 (9.2%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">KWW</td>
<td class="gt_row gt_center" headers="stat_0">33.54 (8.61)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;(Osservazioni mancanti)</td>
<td class="gt_row gt_center" headers="stat_0">47</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">IQ</td>
<td class="gt_row gt_center" headers="stat_0">102.45 (15.42)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;(Osservazioni mancanti)</td>
<td class="gt_row gt_center" headers="stat_0">949</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">married</td>
<td class="gt_row gt_center" headers="stat_0"><br>
</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;1</td>
<td class="gt_row gt_center" headers="stat_0">2,144 (71%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;2</td>
<td class="gt_row gt_center" headers="stat_0">14 (0.5%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;3</td>
<td class="gt_row gt_center" headers="stat_0">3 (&lt;0.1%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;4</td>
<td class="gt_row gt_center" headers="stat_0">155 (5.2%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;5</td>
<td class="gt_row gt_center" headers="stat_0">102 (3.4%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;6</td>
<td class="gt_row gt_center" headers="stat_0">585 (19%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;(Osservazioni mancanti)</td>
<td class="gt_row gt_center" headers="stat_0">7</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">libcrd14</td>
<td class="gt_row gt_center" headers="stat_0">2,021 (67%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;(Osservazioni mancanti)</td>
<td class="gt_row gt_center" headers="stat_0">13</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">exper</td>
<td class="gt_row gt_center" headers="stat_0">8.86 (4.14)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">lwage</td>
<td class="gt_row gt_center" headers="stat_0">6.26 (0.44)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label" style="font-weight: bold">expersq</td>
<td class="gt_row gt_center" headers="stat_0">95.58 (84.62)</td>
</tr>
</tbody><tfoot class="gt_footnotes">
<tr class="odd">
<td colspan="2" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> Mean (SD); n (%)</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="stima-ols-di-base" class="level2">
<h2 class="anchored" data-anchor-id="stima-ols-di-base">Stima OLS di Base</h2>
<p>Iniziamo con il semplice modello linear che include soltanto la variabile <code>educ</code> <span class="math display">\[
\log(wage_i) = \beta_0 + \beta_1 educ_i + u_i
\]</span></p>
<p>Stimiamo il modello per mezzo dei minimi quadrati ordinari (OLS) usando la funzione <code>feols</code> del pacchetto <code>fixest</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">feols</span>(<span class="fu">log</span>(wage) <span class="sc">~</span> educ, <span class="at">data=</span>card, <span class="at">vcov=</span><span class="st">"hetero"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>lm1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: log(wage)
Observations: 3,010
Standard-errors: Heteroskedasticity-robust 
            Estimate Std. Error  t value  Pr(&gt;|t|)    
(Intercept) 5.570882   0.039093 142.5016 &lt; 2.2e-16 ***
educ        0.052094   0.002907  17.9210 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.421249   Adj. R2: 0.098437</code></pre>
</div>
</div>
<p>Il coefficiente stimato è <span class="math inline">\(hat{\beta}_1=0.0521\)</span>. Questa stima è quasi sicuramente distorta per via delle variabili omesse cioè quelle variabili che hanno influire sia sul salario sia sul livello di istruzione. La presenza di queste varibili rende l’assunzione <span class="math inline">\(E(u_i|educ_i)=0\)</span> poco credibile e, di conseguenza, un’interpretazione causale del coefficiente è impossibile.</p>
<p>Possiamo in ogni caso interpretatare il coefficiente stimato come indicatore dell’associazione statistica esistente fra i salari degli individui e il loro livello di istruzione. In particolare, possiamo dire che un anno addizionale di istruzione è associato con una crescita salariale del 5.21%.</p>
</section>
<section id="modello-ols-con-variabili-esogene" class="level2">
<h2 class="anchored" data-anchor-id="modello-ols-con-variabili-esogene">Modello OLS con variabili esogene</h2>
<p>Per attenuare il problema delle variabili omesse possiamo includere nel modello delle variabili che pensiamo possano essere fonte di distorsione e consideriamo il seguente modello:</p>
<p><span id="eq-modello"><span class="math display">\[
\log(wage_i) = \beta_0 + \beta_1 educ_i + \beta_2 exper_i + \beta_3 exper_i^2 + \beta_4 south_i + \beta_5smsa_i + \beta_6 black + u_i.
\tag{1}\]</span></span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lm2 <span class="ot">&lt;-</span> <span class="fu">feols</span>(<span class="fu">log</span>(wage) <span class="sc">~</span> educ <span class="sc">+</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> south <span class="sc">+</span> smsa <span class="sc">+</span> black, <span class="at">data=</span>card, <span class="at">vcov=</span><span class="st">"hetero"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>lm2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: log(wage)
Observations: 3,010
Standard-errors: Heteroskedasticity-robust 
             Estimate Std. Error   t value   Pr(&gt;|t|)    
(Intercept)  4.733664   0.070158  67.47181  &lt; 2.2e-16 ***
educ         0.074009   0.003642  20.32079  &lt; 2.2e-16 ***
exper        0.083596   0.006733  12.41654  &lt; 2.2e-16 ***
I(exper^2)  -0.002241   0.000318  -7.04429 2.3017e-12 ***
south       -0.124862   0.015351  -8.13390 6.0179e-16 ***
smsa         0.161423   0.015175  10.63736  &lt; 2.2e-16 ***
black       -0.189632   0.017432 -10.87809  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.373755   Adj. R2: 0.289088</code></pre>
</div>
</div>
<p>L’inclusione di esperienza lavorativa (anche in forma quadratica per catturare effetti non lineari), la regione geografica (<code>south</code>), l’area metropolitana e <code>black</code> fornisce un controllo più accurato di altri fattori che potrebbero influenzare i salari. In questo nuovo modello, un anno addizionale di istruzione è associato con una crescita salariale del 7.40%.</p>
<p>Per poter interpretatare questa stima come causale, dovremmo essere certi che il nuovo errore non contenga più nessuna variabile che simultaneamente determini il salario ed una delle altre variabili che abbiamo introdotto nel modello. In altre parole, dovremmo essere pronti a sostenare l’assunzione <span id="eq-lm2"><span class="math display">\[
E(u_i|educ_i, exper_i, south, smsa_i, black_i) = 0.
\tag{2}\]</span></span></p>
<p>La variabile che pensiamo possa ancora essere nell’errore è <span class="math inline">\(q_i\)</span>, l’<em>abilità</em> dell’individuo. Questa variabile non osservabile include tratti come la motivazione personale, la resilienza, le abilità sociali, non è osservabile che possono influenzare il livello del salario di un lavoratore.</p>
<p>Ricordiamo che l’esclusione di questa variabile dal modello <a href="#eq-lm2" class="quarto-xref">Equation&nbsp;2</a> risulterà problematica se <span class="math display">\[
E(q_i|educ_i, exper_i, south, smsa_i, black_i) \neq 0.
\]</span> Siamo pronti a considerare <span class="math inline">\(exper_i, south, smsa_i, black_i\)</span> come variabile esogene, cioè variabili che non hanno una relazione sistematica con quelle varibili: le persone che abitano nel sud (<code>south=1</code>) o in un’area metropolitana (<code>smsa=1</code>) non hanno un’abilità superiore ai lavoratori del nord o che vivono in area rurali. Anche per quanto riguarda l’esperienza e il colore della pelle siamo più che pronti ad assumere che non ci sia una sistematica relazione con <span class="math inline">\(q_i\)</span>. Quindi possiamo sostenere a testa alta <span id="eq-eqw"><span class="math display">\[
E(q_i|exper_i, south, smsa_i, black_i)=0,
\tag{3}\]</span></span> e che quindi l’errore (che contiene <span class="math inline">\(q_i\)</span>) non sia sistematicamente associato con <span class="math inline">\(exper_i, south, smsa_i, black_i\)</span>. In gergo, diciamo che queste variabili sono <strong>esogene</strong>. Rimane il problema dell’istruzione. Quasi per devinizione, l’abilità individuale determina il livello di istruzione di un individuo: la motivazione personale, la diligenza e la capacità di perseverare nelle difficoltà sono chiaramente associate con una probabilità più alta di completare un percorso di studi più avanzato. Il risultato è una relazione fra <span class="math inline">\(q_i\)</span> e <span class="math inline">\(educ_i\)</span> quindi, sebbena <a href="#eq-eqw" class="quarto-xref">Equation&nbsp;3</a> possa essere assunta come valida, non possiamo assumere soddisfatta <a href="#eq-lm2" class="quarto-xref">Equation&nbsp;2</a>.</p>
<section id="variabili-strumentali" class="level4">
<h4 class="anchored" data-anchor-id="variabili-strumentali">Variabili strumentali</h4>
<p>David Card ha proposto di “strumentare” i livelli di istruzione usando la prossimità geografica ad una università. Le variabili in questione sono <code>nearc2</code> and <code>nearc4</code>: variabili binari che prendono il valore <span class="math inline">\(1\)</span> se l’individuo risiedeva nel 1966 (le altre variabili si riferiscono al 1976) vicino ad un college di due anni o ad un college di quattro anni.</p>
</section>
<section id="giustificazione-della-validità-degli-strumenti" class="level3">
<h3 class="anchored" data-anchor-id="giustificazione-della-validità-degli-strumenti">Giustificazione della validità degli strumenti</h3>
<p>Per giustificare l’uso di <code>nearc2</code> e <code>nearc4</code> come strumenti per <code>educ</code> è necessario verificare che due condizioni siano soddisfatte:</p>
<ol type="1">
<li><p><strong>Rilevanza</strong>: Gli strumenti devono essere correlati, vedremo meglio in che modo, con la variabile endogena (<code>educ</code>). L’ipotesi è che la prossimità a un istituto di istruzione superiore abbassi i costi dell’istruzione, sia diretti che indiretti, e quindi incrementi la probabilità che un individuo prosegua l’educazione oltre il livello secondario.</p></li>
<li><p><strong>Esogeneità</strong>: Lo strumento non deve essere correlato con l’errore, cioè con l’abilità. In altre parole, la prossimità a un college influenzare i salari degli individui solo attraverso il suo effetto sull’istruzione, e non dovrebbe essere direttamente correlata con altri fattori che influenzano i salari, come l’abilità non osservata o le preferenze lavorative. Vedremo che questa assunzione può essere discutibile, ma per il momento procediamo assumendo che gli strumenti siano endogeni.</p></li>
</ol>
</section>
</section>
<section id="rilevanza" class="level2">
<h2 class="anchored" data-anchor-id="rilevanza">Rilevanza</h2>
<p>Il modo più semplice, ma anche impreciso, di testare la rilevanza degli strumenti è quello di calcolare la correlazione fra <code>educ</code> e <code>nearc2</code> e <code>nearc4</code>. Questo può essere fatto usando il modello linear, visto che nel modello univariato il coefficiente di regressione è il rapporto fra la covarianza fra le variabili e la varianza della variabile dipendente. Se c’è correlazione allora il coefficiente deve essere (significativamente) diverso da zero.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">feols</span>(educ <span class="sc">~</span> nearc2, <span class="at">data=</span>card, <span class="at">vcov =</span> <span class="st">"hetero"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: educ
Observations: 3,010
Standard-errors: Heteroskedasticity-robust 
             Estimate Std. Error   t value  Pr(&gt;|t|)    
(Intercept) 13.150921   0.064510 203.85880 &lt; 2.2e-16 ***
nearc2       0.255258   0.098453   2.59269  0.009569 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 2.67347   Adj. R2: 0.00191</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">feols</span>(educ <span class="sc">~</span> nearc4, <span class="at">data=</span>card, <span class="at">vcov =</span> <span class="st">"hetero"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: educ
Observations: 3,010
Standard-errors: Heteroskedasticity-robust 
             Estimate Std. Error   t value   Pr(&gt;|t|)    
(Intercept) 12.698015   0.090220 140.74510  &lt; 2.2e-16 ***
nearc4       0.829019   0.106694   7.77005 1.0684e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 2.64848   Adj. R2: 0.02048</code></pre>
</div>
</div>
<p>In entrambi i casi, il coefficiente è positivo: esiste un’associazione positiva fra vivere vicino ad un college e il livello di istruzione raggiunto. I coefficienti sono statisticamente significativi: le statistiche <span class="math inline">\(t\)</span>, ottenuti mediante usando uno standard error valido anche in presenza di eteroschedasticità, sono entrambi superiori al livello critico al livello di significatività <span class="math inline">\(\alpha=0.05\)</span>. I due strumenti mostrano però una diversa “forza”: la correlazione fra <code>nearc2</code> e <code>educ</code> è <span class="math inline">\(\sqrt{R^2} = 0.047\)</span> mentre è di <span class="math inline">\(\sqrt{R^2} = 0.144\)</span> fra <code>nearc4</code> e `educ1.</p>
<p>L’esistenza di una semplice correlazione non è comunque evidenza sufficiente a caratterizzare i nostri strumenti come rilveanti. Il modello in <a href="#eq-modello" class="quarto-xref">Equation&nbsp;1</a> ha le seguente form: <span class="math display">\[
y_i = \beta_0 + \beta_1 X_{i} + \beta_2 W_{1i} + \beta_3 W_{2i} + \dots + \beta_{r+1}W_{ri} + u_i,
\]</span> dove <span class="math inline">\(X_i = educ_i\)</span> è la variabile _endogena` e <span class="math inline">\(W_{1i} = exper_i\)</span>, <span class="math inline">\(W_{2i} = exper_i^2\)</span>, <span class="math inline">\(W_{3i} = south_i\)</span>, <span class="math inline">\(W_{4i} = smsa_i\)</span> e <span class="math inline">\(W_{5i} = black_i\)</span> sono le variabili esogene.</p>
<p>In questo modello la condizione di rilevanza è che il coefficiente sullo strumento in una regressione fra la variabile endogena, lo strumento e le variabili esogene sia statisticamente diverso da zero. Nel caso volessimo usare entrambi gli strumenti, dobbiamo testare l’ipotesi nulla che i coefficienti di entrambi gli strumenti siano uguali a zero.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>first_stage_nearc2 <span class="ot">&lt;-</span> <span class="fu">feols</span>(educ <span class="sc">~</span> nearc2 <span class="sc">+</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> south <span class="sc">+</span> smsa <span class="sc">+</span> black, <span class="at">data=</span>card, <span class="at">vcov =</span> <span class="st">"hetero"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>first_stage_nearc4 <span class="ot">&lt;-</span> <span class="fu">feols</span>(educ <span class="sc">~</span> nearc4 <span class="sc">+</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> south <span class="sc">+</span> smsa <span class="sc">+</span> black, <span class="at">data=</span>card, <span class="at">vcov =</span> <span class="st">"hetero"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>first_stage_nearc4_2 <span class="ot">&lt;-</span> <span class="fu">feols</span>(educ <span class="sc">~</span> nearc4 <span class="sc">+</span> nearc2 <span class="sc">+</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> south <span class="sc">+</span> smsa <span class="sc">+</span> black, <span class="at">data=</span>card, <span class="at">vcov =</span> <span class="st">"hetero"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(first_stage_nearc2, first_stage_nearc4, first_stage_nearc4_2, <span class="at">highlight =</span> <span class="fu">list</span>(<span class="at">m1 =</span> <span class="st">"nearc2"</span>, <span class="at">m2 =</span> <span class="st">"nearc4"</span>, <span class="at">m1 =</span> <span class="fu">c</span>(<span class="st">"nearc2"</span>, <span class="st">"nearc4"</span>)), <span class="at">order =</span> <span class="fu">c</span>(<span class="st">"nearc2"</span>, <span class="st">"nearc4"</span>, <span class="st">"exper"</span>, <span class="st">"exper square"</span>, <span class="st">"south"</span>, <span class="st">"smsa"</span>, <span class="st">"black"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 first_stage_nearc2  first_stage_nearc4 first_stage_near..2
Dependent Var.:                educ                educ                educ
                                                                           
nearc2             0.1222. (0.0735)                         0.1077 (0.0731)
nearc4                               0.3373*** (0.0806)  0.3312*** (0.0806)
exper square        0.0007 (0.0017)     0.0007 (0.0017)     0.0007 (0.0017)
exper           -0.4096*** (0.0319) -0.4100*** (0.0320) -0.4095*** (0.0319)
south           -0.3269*** (0.0787) -0.2915*** (0.0785) -0.2787*** (0.0788)
smsa             0.4969*** (0.0816)  0.4039*** (0.0849)  0.3887*** (0.0857)
black            -1.017*** (0.0880)  -1.006*** (0.0878)  -1.013*** (0.0877)
Constant          16.79*** (0.1428)   16.66*** (0.1467)   16.62*** (0.1495)
_______________ ___________________ ___________________ ___________________
S.E. type       Heteroskedast.-rob. Heteroskedast.-rob. Heteroskedast.-rob.
Observations                  3,010               3,010               3,010
R2                          0.47203             0.47447             0.47485
Adj. R2                     0.47098             0.47342             0.47362
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Il coefficiente di <code>nearc2</code> nella regressione riportata nella prima colonna è statisticamente diverso da zero al 10% di significatività (<span class="math inline">\(t=1.66 &gt; 1.64\)</span>). Il coefficiente di <code>nearc4</code> nella regressione riportata nella secondo colonna è statisticamente diverso da zero allo 0.1% di significatività (<span class="math inline">\(t=4.18 &gt; 3.29\)</span>). Per verificare se entrambi i coefficienti della regressione della terza colonna sono entrambi diversi da zero dobbiamo calcolare la statistica di Wald:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>joint_test <span class="ot">&lt;-</span> <span class="fu">linearHypothesis</span>(first_stage_nearc4_2, <span class="fu">c</span>(<span class="st">"nearc2=0"</span>, <span class="st">"nearc4=0"</span>), <span class="at">test =</span> <span class="st">"Chisq"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>joint_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear hypothesis test

Hypothesis:
nearc2 = 0
nearc4 = 0

Model 1: restricted model
Model 2: educ ~ nearc4 + nearc2 + exper + I(exper^2) + south + smsa + 
    black

  Res.Df Df  Chisq Pr(&gt;Chisq)    
1   3004                         
2   3002  2 19.433  6.026e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Rigettiamo l’ipotesi nulla che entrambi i coefficienti siano simultanemeante uguali a zero.[^chisq]</p>
<p>[chisq:] Il test di Wald ha una distribuzione <span class="math inline">\(\chi^2\)</span> con un numero di gradi di libertà pari al numero dei coefficienti che stiamo testando. In questo caso, i gradi di libertà saranno quindi <span class="math inline">\(df=2\)</span>. Il valore critico della <span class="math inline">\(\chi_2^2\)</span> è <span class="math inline">\(5.99\)</span> che è minore del valore del test (<span class="math inline">\(19.43\)</span>). Alternativamente, avremmo potuto usare il <span class="math inline">\(p\)</span>-value. Il <span class="math inline">\(p\)</span>-value è <span class="math inline">\(6.0264295\times 10^{-5}\)</span> che essendo più piccolo di qualsiasi ragionevole livello di significatività induce a rigettare l’ipotesi nulla.</p>
</section>
<section id="secondo-stadio-della-regressione-iv" class="level2">
<h2 class="anchored" data-anchor-id="secondo-stadio-della-regressione-iv">Secondo Stadio della Regressione IV</h2>
<p>Le regressioni della precedente sezione costituiscono il primo stadio nella costruzione dello stimatore TSLS. Nel secondo stadio andiamo a regredire la variabile <code>educ</code> predetta dalle regressioni del primo stadio nei tre casi:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>educ_hat_nearc2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(first_stage_nearc2)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>educ_hat_nearc4 <span class="ot">&lt;-</span> <span class="fu">predict</span>(first_stage_nearc4)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>educ_hat_nearc4_2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(first_stage_nearc4_2)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Includiamo questi valori predetti nel data.frame `card`</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="do">## affinchè siano accessibili da `feols`</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>card<span class="sc">$</span>educ_hat_nearc2 <span class="ot">&lt;-</span> educ_hat_nearc2</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>card<span class="sc">$</span>educ_hat_nearc4 <span class="ot">&lt;-</span> educ_hat_nearc4</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>card<span class="sc">$</span>educ_hat_nearc4_2 <span class="ot">&lt;-</span> educ_hat_nearc4_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>second_stage_nearc2 <span class="ot">&lt;-</span> <span class="fu">feols</span>(<span class="fu">log</span>(wage) <span class="sc">~</span> educ_hat_nearc2 <span class="sc">+</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> south <span class="sc">+</span> smsa <span class="sc">+</span> black, <span class="at">data=</span>card, <span class="at">vcov =</span> <span class="st">"hetero"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>second_stage_nearc4 <span class="ot">&lt;-</span> <span class="fu">feols</span>(<span class="fu">log</span>(wage) <span class="sc">~</span> educ_hat_nearc4 <span class="sc">+</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> south <span class="sc">+</span> smsa <span class="sc">+</span> black, <span class="at">data=</span>card, <span class="at">vcov =</span> <span class="st">"hetero"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>second_stage_nearc4_2 <span class="ot">&lt;-</span> <span class="fu">feols</span>(<span class="fu">log</span>(wage) <span class="sc">~</span> educ_hat_nearc4_2 <span class="sc">+</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> south <span class="sc">+</span> smsa <span class="sc">+</span> black, <span class="at">data=</span>card, <span class="at">vcov =</span> <span class="st">"hetero"</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(second_stage_nearc2, second_stage_nearc4, second_stage_nearc4_2, </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">highlight =</span> <span class="fu">list</span>(<span class="at">m1 =</span> <span class="st">"educ_hat_nearc2"</span>, </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">m2 =</span> <span class="st">"educ_hat_nearc4"</span>, </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">m1 =</span> <span class="fu">c</span>(<span class="st">"educ_hat_nearc2"</span>, </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"educ_hat_nearc4"</span>, </span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"educ_hat_nearc4_2"</span>)), </span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">order =</span> <span class="fu">c</span>(<span class="st">"educ_hat_nearc2"</span>, <span class="st">"educ_hat_nearc4"</span>, </span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"exper"</span>, <span class="st">"exper square"</span>, <span class="st">"south"</span>, <span class="st">"smsa"</span>, <span class="st">"black"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  second_stage_nearc2 second_stage_nearc4 second_stage_nea..2
Dependent Var.:             log(wage)           log(wage)           log(wage)
                                                                             
educ_hat_nearc2     0.3498** (0.1237)                                        
educ_hat_nearc4                         0.1323** (0.0486)                    
educ_hat_nearc4_2                                          0.1608*** (0.0461)
exper square      -0.0024*** (0.0003) -0.0023*** (0.0003) -0.0023*** (0.0003)
exper              0.1967*** (0.0513)  0.1075*** (0.0211)  0.1192*** (0.0202)
south                -0.0304 (0.0458) -0.1049*** (0.0233) -0.0951*** (0.0228)
smsa                  0.0190 (0.0651)  0.1313*** (0.0294)  0.1166*** (0.0281)
black                 0.0887 (0.1262)   -0.1308* (0.0519)   -0.1020* (0.0496)
Constant               0.0926 (2.083)   3.753*** (0.8180)   3.272*** (0.7771)
_________________ ___________________ ___________________ ___________________
S.E. type         Heteroskedast.-rob. Heteroskedast.-rob. Heteroskedast.-rob.
Observations                    3,010               3,010               3,010
R2                            0.18739             0.18706             0.18831
Adj. R2                       0.18576             0.18543             0.18668
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Un problem per l’interpretazione della tavola precedente è che gli errori standard non sono corretti. Per ottenere quelli corretti dobbiamo utilizzare la funzione <code>feols</code> in maniera che i due stadi siano calcolati internamente cosicchè sia possibile aggiunstare gli errori standard in maniera tale che tengano conto del fatto che le variabili <code>educ_hat_nearc2</code> e <code>educ_hat_nearc4</code> sono le predizioni dei primi stadi.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>tsls_nearc2 <span class="ot">&lt;-</span> <span class="fu">feols</span>(<span class="fu">log</span>(wage) <span class="sc">~</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> south <span class="sc">+</span> smsa <span class="sc">+</span> black </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>                     <span class="sc">|</span> educ <span class="sc">~</span> nearc2, <span class="at">data=</span>card, <span class="at">vcov =</span> <span class="st">"hetero"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>tsls_nearc4 <span class="ot">&lt;-</span> <span class="fu">feols</span>(<span class="fu">log</span>(wage) <span class="sc">~</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> south <span class="sc">+</span> smsa <span class="sc">+</span> black </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>                     <span class="sc">|</span> educ <span class="sc">~</span> nearc4, <span class="at">data=</span>card, <span class="at">vcov =</span> <span class="st">"hetero"</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>tsls_nearc4_2 <span class="ot">&lt;-</span> <span class="fu">feols</span>(<span class="fu">log</span>(wage) <span class="sc">~</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> south <span class="sc">+</span> smsa <span class="sc">+</span> black </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>                       <span class="sc">|</span> educ <span class="sc">~</span> nearc2<span class="sc">+</span>nearc4, <span class="at">data=</span>card, <span class="at">vcov =</span> <span class="st">"hetero"</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(tsls_nearc2, tsls_nearc4, tsls_nearc4_2, </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">highlight =</span> <span class="st">"educ"</span>, </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">order =</span> <span class="fu">c</span>(<span class="st">"educ"</span>, <span class="st">"exper"</span>, <span class="st">"exper square"</span>, <span class="st">"south"</span>, <span class="st">"smsa"</span>, <span class="st">"black"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        tsls_nearc2         tsls_nearc4       tsls_nearc4_2
Dependent Var.:           log(wage)           log(wage)           log(wage)
                                                                           
educ               0.3498. (0.2023)   0.1323** (0.0486)  0.1608*** (0.0486)
exper square    -0.0024*** (0.0006) -0.0023*** (0.0003) -0.0023*** (0.0004)
exper              0.1967* (0.0842)  0.1075*** (0.0211)  0.1192*** (0.0213)
south              -0.0304 (0.0738) -0.1049*** (0.0229) -0.0951*** (0.0234)
smsa                0.0190 (0.1084)  0.1313*** (0.0298)  0.1166*** (0.0303)
black               0.0887 (0.2079)   -0.1308* (0.0515)   -0.1020. (0.0521)
Constant             0.0926 (3.406)   3.753*** (0.8177)   3.272*** (0.8178)
_______________ ___________________ ___________________ ___________________
S.E. type       Heteroskedast.-rob. Heteroskedast.-rob. Heteroskedast.-rob.
Observations                  3,010               3,010               3,010
R2                          -1.1715             0.22520             0.14551
Adj. R2                     -1.1759             0.22365             0.14381
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>I coefficienti stimati da questa ultima serie di comandi e riportati nella tabella sono identici a quelli ottenuti alla procedura a due stadi manuale. La differenza consiste negli errori standard che sono diversi da quelli ottenuti dalla prima procedura.</p>
<p>L’analisi delle stime OLS e TSLS basata sulle tabelle fornite offre una visione approfondita di come i due metodi trattano l’endogeneità dell’istruzione nei modelli di salario. I dati mostrano come gli stimatori TSLS correggano il bias che affligge le stime OLS a causa delle variabili omesse o della correlazione tra le variabili esplicative e il termine di errore.</p>
<p>Riassumendo i nostri risultati:</p>
<section id="risultati-ols" class="level4">
<h4 class="anchored" data-anchor-id="risultati-ols">Risultati OLS</h4>
<ol type="1">
<li><p><strong>Modello OLS Semplice (lm1)</strong>: Questo modello stima che ogni anno aggiuntivo di istruzione è associato ad una crescita del salario del 5.2%.</p></li>
<li><p><strong>Modello OLS Esteso (lm2)</strong>: Introducendo controlli per l’esperienza, l’esperienza quadrata, la regione (south), l’area metropolitana (smsa), e la razza (black), il coefficiente dell’istruzione passa a 0.0740 (aumento del 7.4% del salario per ogni anno di istruzione addizionale).</p></li>
</ol>
</section>
<section id="risultati-tsls" class="level4">
<h4 class="anchored" data-anchor-id="risultati-tsls">Risultati TSLS</h4>
<ol type="1">
<li><p><strong>Modello TSLS con <code>nearc2</code> (tsls_nearc2)</strong>: L’uso di <code>nearc2</code> come strumento per l’istruzione mostra un coefficiente molto più alto per l’istruzione (35%). Questo coefficiente non è statisticamente significativo al livello convenzionale. L’imprecisone è probabilmente dovuta al fatto che questo strumento sebbene soddisfi la condizione di rilevanza, non ha una “forte” correlazione con <code>educ</code>.</p></li>
<li><p><strong>Modello TSLS con <code>nearc4</code> (tsls_nearc4)</strong>: Il coefficiente per l’istruzione è 0.1323, statisticamente significativo al livello del 1%.</p></li>
<li><p><strong>Modello TSLS con <code>nearc2</code> e <code>nearc4</code> (tsls_nearc4_2)</strong>: L’uso combinato di entrambi gli strumenti produce un coefficiente di 0.1608, anch’esso significativo e indicativo di un ritorno dell’istruzione più elevato rispetto all’OLS esteso.</p></li>
</ol>
<p>I risultati TSLS indicano che, quando si corregge per l’endogeneità utilizzando variabili strumentali appropriate, i ritorni stimati dell’istruzione sui salari sono significativamente più alti rispetto alle stime OLS, che possono soffrire di bias dovuto a variabili omesse o misurate in modo errato.</p>
</section>
</section>
<section id="test-per-endogeneità" class="level2">
<h2 class="anchored" data-anchor-id="test-per-endogeneità">Test per endogeneità</h2>
<p>Il test di endogeneità, noto anche come test J è un test usato per verificare se gli strumenti utilizzati in un modello con variabili strumentali sono esogeni.</p>
<p>La procedura inizia con la stima dell’equazione di interesse tramite TSLS, utilizzando tutti gli strumenti disponibili. Usando questa regressione, vengono calcolati i residui</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>u_hat <span class="ot">&lt;-</span> <span class="fu">resid</span>(tsls_nearc4_2)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>card<span class="sc">$</span>u_hat <span class="ot">&lt;-</span> u_hat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Questi residui vengono utilizzati come variabile dipendente in una nuova regressione, dove le variabili indipendenti includono sia gli strumenti (<code>nearc2</code> e <code>nearc4</code>) sia le altre variabili esogene del modello originale (<code>exper</code>, <code>exper^2</code>, <code>south</code>, <code>smsa</code>, <code>black</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>jreg <span class="ot">&lt;-</span> <span class="fu">feols</span>(u_hat<span class="sc">~</span>nearc2 <span class="sc">+</span> nearc4<span class="sc">+</span>exper<span class="sc">+</span>exper<span class="sc">^</span><span class="dv">2</span><span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>                south<span class="sc">+</span>smsa<span class="sc">+</span>black, <span class="at">data =</span> card, </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">vcov =</span> <span class="st">"hetero"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Il cuore del test è il test Wald per verificare se i coefficienti associati agli strumenti siano statisticamente diversi da zero.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(jreg, <span class="fu">c</span>(<span class="st">"nearc2=0"</span>, <span class="st">"nearc4=0"</span>), <span class="at">test=</span><span class="st">"Chisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear hypothesis test

Hypothesis:
nearc2 = 0
nearc4 = 0

Model 1: restricted model
Model 2: u_hat ~ nearc2 + nearc4 + exper + I(exper^2) + south + smsa + 
    black

  Res.Df Df  Chisq Pr(&gt;Chisq)
1   3004                     
2   3002  2 2.6552     0.2651</code></pre>
</div>
</div>
<p>Per analizzare il risultato del test, bisogna tenere in mente che i gradi di libertà di questo test non corrispondono al numero delle restrizioni testate (nel caso specifico, due: <code>nearc2 = 0</code> e <code>nearc4 = 0</code>), ma piuttosto al numero di strumenti (2) meno il numero di variabili endogene (1). In questo esempio, la statistica chi-quadrato risultante è <span class="math inline">\(2.6552\)</span>, che deve essere confrontata con il valore critico della distribuzione chi-quadrato con un grado di libertà (3.84). Quindi, visto 2.6552 &lt; 3.84, non possiamo rigettare l’ipotesi nulla che entrambi i coefficienti siano uguali a zero. Il <span class="math inline">\(J\)</span> test suggerisce quindi l’esogeneità degli strumenti.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/gragusa\.org\/econometria\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>